<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED value CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED><!ATTLIST buffer-attribute name CDATA #REQUIRED value CDATA #IMPLIED>]><context name="xml" description="no-OS/projects/NO_OS_PROJECT NO_OS_VERSION"><context-attribute name="fw_version" value="v2.0.0-rc.0" /><context-attribute name="commit_version" value="fa61176" /><context-attribute name="hw_carrier" value="SDP_K1" /><context-attribute name="hw_mezzanine" value="EVAL-AD5529RARDZ" /><context-attribute name="hw_name" value="EVAL-AD5529RARDZ" /><context-attribute name="uri" value="serial:/dev/ttyS0,230400,8n1n" /><context-attribute name="serial,port" value="/dev/ttyS0" /><context-attribute name="serial,description" value="ttyS0" /><device id="iio:device0" name="ad5529r"><channel id="voltage0" name="Chn0" type="output"><scan-element index="0" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage0_raw" value="0" /><attribute name="scale" filename="out_voltage0_scale" value="0.0762951076" /><attribute name="offset" filename="out_voltage0_offset" value="0" /><attribute name="input_register_a" filename="out_voltage0_input_register_a" value="0" /><attribute name="input_register_b" filename="out_voltage0_input_register_b" value="0" /><attribute name="output_state" filename="out_voltage0_output_state" value="disable" /><attribute name="output_state_available" filename="out_voltage0_output_state_available" value="disable enable" /><attribute name="range_sel" filename="out_voltage0_range_sel" value="unipolar_5V" /><attribute name="range_sel_available" filename="out_voltage0_range_sel_available" value="unipolar_5V unipolar_10V unipolar_20V unipolar_40V bipolar_5V bipolar_10V bipolar_15V bipolar_20V" /><attribute name="hw_sw_sel" filename="out_voltage0_hw_sw_sel" value="hw" /><attribute name="hw_sw_sel_available" filename="out_voltage0_hw_sw_sel_available" value="hw sw" /><attribute name="func_sel" filename="out_voltage0_func_sel" value="disable" /><attribute name="func_sel_available" filename="out_voltage0_func_sel_available" value="disable ldac_toggle dither sawtooth triangular" /><attribute name="hw_ldac_pin_sel" filename="out_voltage0_hw_ldac_pin_sel" value="ldac_toggle_0" /><attribute name="hw_ldac_pin_sel_available" filename="out_voltage0_hw_ldac_pin_sel_available" value="ldac_toggle_0 ldac_toggle_1 ldac_toggle_2 ldac_toggle_3" /><attribute name="hw_ldac_edge_sel" filename="out_voltage0_hw_ldac_edge_sel" value="rising_edge" /><attribute name="hw_ldac_edge_sel_available" filename="out_voltage0_hw_ldac_edge_sel_available" value="rising_edge falling_edge any_edge" /><attribute name="dither_period_factor" filename="out_voltage0_dither_period_factor" value="128" /><attribute name="dither_period_factor_available" filename="out_voltage0_dither_period_factor_available" value="2 4 8 16 32 64 128" /><attribute name="dither_phase" filename="out_voltage0_dither_phase" value="0" /><attribute name="dither_phase_available" filename="out_voltage0_dither_phase_available" value="0 90 180 270" /><attribute name="ramp_step_size" filename="out_voltage0_ramp_step_size" value="0" /></channel><channel id="voltage1" name="Chn1" type="output"><scan-element index="1" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage1_raw" value="0" /><attribute name="scale" filename="out_voltage1_scale" value="0.0762951076" /><attribute name="offset" filename="out_voltage1_offset" value="0" /><attribute name="input_register_a" filename="out_voltage1_input_register_a" value="0" /><attribute name="input_register_b" filename="out_voltage1_input_register_b" value="0" /><attribute name="output_state" filename="out_voltage1_output_state" value="disable" /><attribute name="output_state_available" filename="out_voltage1_output_state_available" value="disable enable" /><attribute name="range_sel" filename="out_voltage1_range_sel" value="unipolar_5V" /><attribute name="range_sel_available" filename="out_voltage1_range_sel_available" value="unipolar_5V unipolar_10V unipolar_20V unipolar_40V bipolar_5V bipolar_10V bipolar_15V bipolar_20V" /><attribute name="hw_sw_sel" filename="out_voltage1_hw_sw_sel" value="hw" /><attribute name="hw_sw_sel_available" filename="out_voltage1_hw_sw_sel_available" value="hw sw" /><attribute name="func_sel" filename="out_voltage1_func_sel" value="disable" /><attribute name="func_sel_available" filename="out_voltage1_func_sel_available" value="disable ldac_toggle dither sawtooth triangular" /><attribute name="hw_ldac_pin_sel" filename="out_voltage1_hw_ldac_pin_sel" value="ldac_toggle_0" /><attribute name="hw_ldac_pin_sel_available" filename="out_voltage1_hw_ldac_pin_sel_available" value="ldac_toggle_0 ldac_toggle_1 ldac_toggle_2 ldac_toggle_3" /><attribute name="hw_ldac_edge_sel" filename="out_voltage1_hw_ldac_edge_sel" value="rising_edge" /><attribute name="hw_ldac_edge_sel_available" filename="out_voltage1_hw_ldac_edge_sel_available" value="rising_edge falling_edge any_edge" /><attribute name="dither_period_factor" filename="out_voltage1_dither_period_factor" value="128" /><attribute name="dither_period_factor_available" filename="out_voltage1_dither_period_factor_available" value="2 4 8 16 32 64 128" /><attribute name="dither_phase" filename="out_voltage1_dither_phase" value="0" /><attribute name="dither_phase_available" filename="out_voltage1_dither_phase_available" value="0 90 180 270" /><attribute name="ramp_step_size" filename="out_voltage1_ramp_step_size" value="0" /></channel><channel id="voltage2" name="Chn2" type="output"><scan-element index="2" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage2_raw" value="0" /><attribute name="scale" filename="out_voltage2_scale" value="0.0762951076" /><attribute name="offset" filename="out_voltage2_offset" value="0" /><attribute name="input_register_a" filename="out_voltage2_input_register_a" value="0" /><attribute name="input_register_b" filename="out_voltage2_input_register_b" value="0" /><attribute name="output_state" filename="out_voltage2_output_state" value="disable" /><attribute name="output_state_available" filename="out_voltage2_output_state_available" value="disable enable" /><attribute name="range_sel" filename="out_voltage2_range_sel" value="unipolar_5V" /><attribute name="range_sel_available" filename="out_voltage2_range_sel_available" value="unipolar_5V unipolar_10V unipolar_20V unipolar_40V bipolar_5V bipolar_10V bipolar_15V bipolar_20V" /><attribute name="hw_sw_sel" filename="out_voltage2_hw_sw_sel" value="hw" /><attribute name="hw_sw_sel_available" filename="out_voltage2_hw_sw_sel_available" value="hw sw" /><attribute name="func_sel" filename="out_voltage2_func_sel" value="disable" /><attribute name="func_sel_available" filename="out_voltage2_func_sel_available" value="disable ldac_toggle dither sawtooth triangular" /><attribute name="hw_ldac_pin_sel" filename="out_voltage2_hw_ldac_pin_sel" value="ldac_toggle_0" /><attribute name="hw_ldac_pin_sel_available" filename="out_voltage2_hw_ldac_pin_sel_available" value="ldac_toggle_0 ldac_toggle_1 ldac_toggle_2 ldac_toggle_3" /><attribute name="hw_ldac_edge_sel" filename="out_voltage2_hw_ldac_edge_sel" value="rising_edge" /><attribute name="hw_ldac_edge_sel_available" filename="out_voltage2_hw_ldac_edge_sel_available" value="rising_edge falling_edge any_edge" /><attribute name="dither_period_factor" filename="out_voltage2_dither_period_factor" value="128" /><attribute name="dither_period_factor_available" filename="out_voltage2_dither_period_factor_available" value="2 4 8 16 32 64 128" /><attribute name="dither_phase" filename="out_voltage2_dither_phase" value="0" /><attribute name="dither_phase_available" filename="out_voltage2_dither_phase_available" value="0 90 180 270" /><attribute name="ramp_step_size" filename="out_voltage2_ramp_step_size" value="0" /></channel><channel id="voltage3" name="Chn3" type="output"><scan-element index="3" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage3_raw" value="0" /><attribute name="scale" filename="out_voltage3_scale" value="0.0762951076" /><attribute name="offset" filename="out_voltage3_offset" value="0" /><attribute name="input_register_a" filename="out_voltage3_input_register_a" value="0" /><attribute name="input_register_b" filename="out_voltage3_input_register_b" value="0" /><attribute name="output_state" filename="out_voltage3_output_state" value="disable" /><attribute name="output_state_available" filename="out_voltage3_output_state_available" value="disable enable" /><attribute name="range_sel" filename="out_voltage3_range_sel" value="unipolar_5V" /><attribute name="range_sel_available" filename="out_voltage3_range_sel_available" value="unipolar_5V unipolar_10V unipolar_20V unipolar_40V bipolar_5V bipolar_10V bipolar_15V bipolar_20V" /><attribute name="hw_sw_sel" filename="out_voltage3_hw_sw_sel" value="hw" /><attribute name="hw_sw_sel_available" filename="out_voltage3_hw_sw_sel_available" value="hw sw" /><attribute name="func_sel" filename="out_voltage3_func_sel" value="disable" /><attribute name="func_sel_available" filename="out_voltage3_func_sel_available" value="disable ldac_toggle dither sawtooth triangular" /><attribute name="hw_ldac_pin_sel" filename="out_voltage3_hw_ldac_pin_sel" value="ldac_toggle_0" /><attribute name="hw_ldac_pin_sel_available" filename="out_voltage3_hw_ldac_pin_sel_available" value="ldac_toggle_0 ldac_toggle_1 ldac_toggle_2 ldac_toggle_3" /><attribute name="hw_ldac_edge_sel" filename="out_voltage3_hw_ldac_edge_sel" value="rising_edge" /><attribute name="hw_ldac_edge_sel_available" filename="out_voltage3_hw_ldac_edge_sel_available" value="rising_edge falling_edge any_edge" /><attribute name="dither_period_factor" filename="out_voltage3_dither_period_factor" value="128" /><attribute name="dither_period_factor_available" filename="out_voltage3_dither_period_factor_available" value="2 4 8 16 32 64 128" /><attribute name="dither_phase" filename="out_voltage3_dither_phase" value="0" /><attribute name="dither_phase_available" filename="out_voltage3_dither_phase_available" value="0 90 180 270" /><attribute name="ramp_step_size" filename="out_voltage3_ramp_step_size" value="0" /></channel><channel id="voltage4" name="Chn4" type="output"><scan-element index="4" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage4_raw" value="0" /><attribute name="scale" filename="out_voltage4_scale" value="0.0762951076" /><attribute name="offset" filename="out_voltage4_offset" value="0" /><attribute name="input_register_a" filename="out_voltage4_input_register_a" value="0" /><attribute name="input_register_b" filename="out_voltage4_input_register_b" value="0" /><attribute name="output_state" filename="out_voltage4_output_state" value="disable" /><attribute name="output_state_available" filename="out_voltage4_output_state_available" value="disable enable" /><attribute name="range_sel" filename="out_voltage4_range_sel" value="unipolar_5V" /><attribute name="range_sel_available" filename="out_voltage4_range_sel_available" value="unipolar_5V unipolar_10V unipolar_20V unipolar_40V bipolar_5V bipolar_10V bipolar_15V bipolar_20V" /><attribute name="hw_sw_sel" filename="out_voltage4_hw_sw_sel" value="hw" /><attribute name="hw_sw_sel_available" filename="out_voltage4_hw_sw_sel_available" value="hw sw" /><attribute name="func_sel" filename="out_voltage4_func_sel" value="disable" /><attribute name="func_sel_available" filename="out_voltage4_func_sel_available" value="disable ldac_toggle dither sawtooth triangular" /><attribute name="hw_ldac_pin_sel" filename="out_voltage4_hw_ldac_pin_sel" value="ldac_toggle_0" /><attribute name="hw_ldac_pin_sel_available" filename="out_voltage4_hw_ldac_pin_sel_available" value="ldac_toggle_0 ldac_toggle_1 ldac_toggle_2 ldac_toggle_3" /><attribute name="hw_ldac_edge_sel" filename="out_voltage4_hw_ldac_edge_sel" value="rising_edge" /><attribute name="hw_ldac_edge_sel_available" filename="out_voltage4_hw_ldac_edge_sel_available" value="rising_edge falling_edge any_edge" /><attribute name="dither_period_factor" filename="out_voltage4_dither_period_factor" value="128" /><attribute name="dither_period_factor_available" filename="out_voltage4_dither_period_factor_available" value="2 4 8 16 32 64 128" /><attribute name="dither_phase" filename="out_voltage4_dither_phase" value="0" /><attribute name="dither_phase_available" filename="out_voltage4_dither_phase_available" value="0 90 180 270" /><attribute name="ramp_step_size" filename="out_voltage4_ramp_step_size" value="0" /></channel><channel id="voltage5" name="Chn5" type="output"><scan-element index="5" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage5_raw" value="0" /><attribute name="scale" filename="out_voltage5_scale" value="0.0762951076" /><attribute name="offset" filename="out_voltage5_offset" value="0" /><attribute name="input_register_a" filename="out_voltage5_input_register_a" value="0" /><attribute name="input_register_b" filename="out_voltage5_input_register_b" value="0" /><attribute name="output_state" filename="out_voltage5_output_state" value="disable" /><attribute name="output_state_available" filename="out_voltage5_output_state_available" value="disable enable" /><attribute name="range_sel" filename="out_voltage5_range_sel" value="unipolar_5V" /><attribute name="range_sel_available" filename="out_voltage5_range_sel_available" value="unipolar_5V unipolar_10V unipolar_20V unipolar_40V bipolar_5V bipolar_10V bipolar_15V bipolar_20V" /><attribute name="hw_sw_sel" filename="out_voltage5_hw_sw_sel" value="hw" /><attribute name="hw_sw_sel_available" filename="out_voltage5_hw_sw_sel_available" value="hw sw" /><attribute name="func_sel" filename="out_voltage5_func_sel" value="disable" /><attribute name="func_sel_available" filename="out_voltage5_func_sel_available" value="disable ldac_toggle dither sawtooth triangular" /><attribute name="hw_ldac_pin_sel" filename="out_voltage5_hw_ldac_pin_sel" value="ldac_toggle_0" /><attribute name="hw_ldac_pin_sel_available" filename="out_voltage5_hw_ldac_pin_sel_available" value="ldac_toggle_0 ldac_toggle_1 ldac_toggle_2 ldac_toggle_3" /><attribute name="hw_ldac_edge_sel" filename="out_voltage5_hw_ldac_edge_sel" value="rising_edge" /><attribute name="hw_ldac_edge_sel_available" filename="out_voltage5_hw_ldac_edge_sel_available" value="rising_edge falling_edge any_edge" /><attribute name="dither_period_factor" filename="out_voltage5_dither_period_factor" value="128" /><attribute name="dither_period_factor_available" filename="out_voltage5_dither_period_factor_available" value="2 4 8 16 32 64 128" /><attribute name="dither_phase" filename="out_voltage5_dither_phase" value="0" /><attribute name="dither_phase_available" filename="out_voltage5_dither_phase_available" value="0 90 180 270" /><attribute name="ramp_step_size" filename="out_voltage5_ramp_step_size" value="0" /></channel><channel id="voltage6" name="Chn6" type="output"><scan-element index="6" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage6_raw" value="0" /><attribute name="scale" filename="out_voltage6_scale" value="0.0762951076" /><attribute name="offset" filename="out_voltage6_offset" value="0" /><attribute name="input_register_a" filename="out_voltage6_input_register_a" value="0" /><attribute name="input_register_b" filename="out_voltage6_input_register_b" value="0" /><attribute name="output_state" filename="out_voltage6_output_state" value="disable" /><attribute name="output_state_available" filename="out_voltage6_output_state_available" value="disable enable" /><attribute name="range_sel" filename="out_voltage6_range_sel" value="unipolar_5V" /><attribute name="range_sel_available" filename="out_voltage6_range_sel_available" value="unipolar_5V unipolar_10V unipolar_20V unipolar_40V bipolar_5V bipolar_10V bipolar_15V bipolar_20V" /><attribute name="hw_sw_sel" filename="out_voltage6_hw_sw_sel" value="hw" /><attribute name="hw_sw_sel_available" filename="out_voltage6_hw_sw_sel_available" value="hw sw" /><attribute name="func_sel" filename="out_voltage6_func_sel" value="disable" /><attribute name="func_sel_available" filename="out_voltage6_func_sel_available" value="disable ldac_toggle dither sawtooth triangular" /><attribute name="hw_ldac_pin_sel" filename="out_voltage6_hw_ldac_pin_sel" value="ldac_toggle_0" /><attribute name="hw_ldac_pin_sel_available" filename="out_voltage6_hw_ldac_pin_sel_available" value="ldac_toggle_0 ldac_toggle_1 ldac_toggle_2 ldac_toggle_3" /><attribute name="hw_ldac_edge_sel" filename="out_voltage6_hw_ldac_edge_sel" value="rising_edge" /><attribute name="hw_ldac_edge_sel_available" filename="out_voltage6_hw_ldac_edge_sel_available" value="rising_edge falling_edge any_edge" /><attribute name="dither_period_factor" filename="out_voltage6_dither_period_factor" value="128" /><attribute name="dither_period_factor_available" filename="out_voltage6_dither_period_factor_available" value="2 4 8 16 32 64 128" /><attribute name="dither_phase" filename="out_voltage6_dither_phase" value="0" /><attribute name="dither_phase_available" filename="out_voltage6_dither_phase_available" value="0 90 180 270" /><attribute name="ramp_step_size" filename="out_voltage6_ramp_step_size" value="0" /></channel><channel id="voltage7" name="Chn7" type="output"><scan-element index="7" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage7_raw" value="0" /><attribute name="scale" filename="out_voltage7_scale" value="0.0762951076" /><attribute name="offset" filename="out_voltage7_offset" value="0" /><attribute name="input_register_a" filename="out_voltage7_input_register_a" value="0" /><attribute name="input_register_b" filename="out_voltage7_input_register_b" value="0" /><attribute name="output_state" filename="out_voltage7_output_state" value="disable" /><attribute name="output_state_available" filename="out_voltage7_output_state_available" value="disable enable" /><attribute name="range_sel" filename="out_voltage7_range_sel" value="unipolar_5V" /><attribute name="range_sel_available" filename="out_voltage7_range_sel_available" value="unipolar_5V unipolar_10V unipolar_20V unipolar_40V bipolar_5V bipolar_10V bipolar_15V bipolar_20V" /><attribute name="hw_sw_sel" filename="out_voltage7_hw_sw_sel" value="hw" /><attribute name="hw_sw_sel_available" filename="out_voltage7_hw_sw_sel_available" value="hw sw" /><attribute name="func_sel" filename="out_voltage7_func_sel" value="disable" /><attribute name="func_sel_available" filename="out_voltage7_func_sel_available" value="disable ldac_toggle dither sawtooth triangular" /><attribute name="hw_ldac_pin_sel" filename="out_voltage7_hw_ldac_pin_sel" value="ldac_toggle_0" /><attribute name="hw_ldac_pin_sel_available" filename="out_voltage7_hw_ldac_pin_sel_available" value="ldac_toggle_0 ldac_toggle_1 ldac_toggle_2 ldac_toggle_3" /><attribute name="hw_ldac_edge_sel" filename="out_voltage7_hw_ldac_edge_sel" value="rising_edge" /><attribute name="hw_ldac_edge_sel_available" filename="out_voltage7_hw_ldac_edge_sel_available" value="rising_edge falling_edge any_edge" /><attribute name="dither_period_factor" filename="out_voltage7_dither_period_factor" value="128" /><attribute name="dither_period_factor_available" filename="out_voltage7_dither_period_factor_available" value="2 4 8 16 32 64 128" /><attribute name="dither_phase" filename="out_voltage7_dither_phase" value="0" /><attribute name="dither_phase_available" filename="out_voltage7_dither_phase_available" value="0 90 180 270" /><attribute name="ramp_step_size" filename="out_voltage7_ramp_step_size" value="0" /></channel><channel id="voltage8" name="Chn8" type="output"><scan-element index="8" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage8_raw" value="0" /><attribute name="scale" filename="out_voltage8_scale" value="0.0762951076" /><attribute name="offset" filename="out_voltage8_offset" value="0" /><attribute name="input_register_a" filename="out_voltage8_input_register_a" value="0" /><attribute name="input_register_b" filename="out_voltage8_input_register_b" value="0" /><attribute name="output_state" filename="out_voltage8_output_state" value="disable" /><attribute name="output_state_available" filename="out_voltage8_output_state_available" value="disable enable" /><attribute name="range_sel" filename="out_voltage8_range_sel" value="unipolar_5V" /><attribute name="range_sel_available" filename="out_voltage8_range_sel_available" value="unipolar_5V unipolar_10V unipolar_20V unipolar_40V bipolar_5V bipolar_10V bipolar_15V bipolar_20V" /><attribute name="hw_sw_sel" filename="out_voltage8_hw_sw_sel" value="hw" /><attribute name="hw_sw_sel_available" filename="out_voltage8_hw_sw_sel_available" value="hw sw" /><attribute name="func_sel" filename="out_voltage8_func_sel" value="disable" /><attribute name="func_sel_available" filename="out_voltage8_func_sel_available" value="disable ldac_toggle dither sawtooth triangular" /><attribute name="hw_ldac_pin_sel" filename="out_voltage8_hw_ldac_pin_sel" value="ldac_toggle_0" /><attribute name="hw_ldac_pin_sel_available" filename="out_voltage8_hw_ldac_pin_sel_available" value="ldac_toggle_0 ldac_toggle_1 ldac_toggle_2 ldac_toggle_3" /><attribute name="hw_ldac_edge_sel" filename="out_voltage8_hw_ldac_edge_sel" value="rising_edge" /><attribute name="hw_ldac_edge_sel_available" filename="out_voltage8_hw_ldac_edge_sel_available" value="rising_edge falling_edge any_edge" /><attribute name="dither_period_factor" filename="out_voltage8_dither_period_factor" value="128" /><attribute name="dither_period_factor_available" filename="out_voltage8_dither_period_factor_available" value="2 4 8 16 32 64 128" /><attribute name="dither_phase" filename="out_voltage8_dither_phase" value="0" /><attribute name="dither_phase_available" filename="out_voltage8_dither_phase_available" value="0 90 180 270" /><attribute name="ramp_step_size" filename="out_voltage8_ramp_step_size" value="0" /></channel><channel id="voltage9" name="Chn9" type="output"><scan-element index="9" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage9_raw" value="0" /><attribute name="scale" filename="out_voltage9_scale" value="0.0762951076" /><attribute name="offset" filename="out_voltage9_offset" value="0" /><attribute name="input_register_a" filename="out_voltage9_input_register_a" value="0" /><attribute name="input_register_b" filename="out_voltage9_input_register_b" value="0" /><attribute name="output_state" filename="out_voltage9_output_state" value="disable" /><attribute name="output_state_available" filename="out_voltage9_output_state_available" value="disable enable" /><attribute name="range_sel" filename="out_voltage9_range_sel" value="unipolar_5V" /><attribute name="range_sel_available" filename="out_voltage9_range_sel_available" value="unipolar_5V unipolar_10V unipolar_20V unipolar_40V bipolar_5V bipolar_10V bipolar_15V bipolar_20V" /><attribute name="hw_sw_sel" filename="out_voltage9_hw_sw_sel" value="hw" /><attribute name="hw_sw_sel_available" filename="out_voltage9_hw_sw_sel_available" value="hw sw" /><attribute name="func_sel" filename="out_voltage9_func_sel" value="disable" /><attribute name="func_sel_available" filename="out_voltage9_func_sel_available" value="disable ldac_toggle dither sawtooth triangular" /><attribute name="hw_ldac_pin_sel" filename="out_voltage9_hw_ldac_pin_sel" value="ldac_toggle_0" /><attribute name="hw_ldac_pin_sel_available" filename="out_voltage9_hw_ldac_pin_sel_available" value="ldac_toggle_0 ldac_toggle_1 ldac_toggle_2 ldac_toggle_3" /><attribute name="hw_ldac_edge_sel" filename="out_voltage9_hw_ldac_edge_sel" value="rising_edge" /><attribute name="hw_ldac_edge_sel_available" filename="out_voltage9_hw_ldac_edge_sel_available" value="rising_edge falling_edge any_edge" /><attribute name="dither_period_factor" filename="out_voltage9_dither_period_factor" value="128" /><attribute name="dither_period_factor_available" filename="out_voltage9_dither_period_factor_available" value="2 4 8 16 32 64 128" /><attribute name="dither_phase" filename="out_voltage9_dither_phase" value="0" /><attribute name="dither_phase_available" filename="out_voltage9_dither_phase_available" value="0 90 180 270" /><attribute name="ramp_step_size" filename="out_voltage9_ramp_step_size" value="0" /></channel><channel id="voltage10" name="Chn10" type="output"><scan-element index="10" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage10_raw" value="0" /><attribute name="scale" filename="out_voltage10_scale" value="0.0762951076" /><attribute name="offset" filename="out_voltage10_offset" value="0" /><attribute name="input_register_a" filename="out_voltage10_input_register_a" value="0" /><attribute name="input_register_b" filename="out_voltage10_input_register_b" value="0" /><attribute name="output_state" filename="out_voltage10_output_state" value="disable" /><attribute name="output_state_available" filename="out_voltage10_output_state_available" value="disable enable" /><attribute name="range_sel" filename="out_voltage10_range_sel" value="unipolar_5V" /><attribute name="range_sel_available" filename="out_voltage10_range_sel_available" value="unipolar_5V unipolar_10V unipolar_20V unipolar_40V bipolar_5V bipolar_10V bipolar_15V bipolar_20V" /><attribute name="hw_sw_sel" filename="out_voltage10_hw_sw_sel" value="hw" /><attribute name="hw_sw_sel_available" filename="out_voltage10_hw_sw_sel_available" value="hw sw" /><attribute name="func_sel" filename="out_voltage10_func_sel" value="disable" /><attribute name="func_sel_available" filename="out_voltage10_func_sel_available" value="disable ldac_toggle dither sawtooth triangular" /><attribute name="hw_ldac_pin_sel" filename="out_voltage10_hw_ldac_pin_sel" value="ldac_toggle_0" /><attribute name="hw_ldac_pin_sel_available" filename="out_voltage10_hw_ldac_pin_sel_available" value="ldac_toggle_0 ldac_toggle_1 ldac_toggle_2 ldac_toggle_3" /><attribute name="hw_ldac_edge_sel" filename="out_voltage10_hw_ldac_edge_sel" value="rising_edge" /><attribute name="hw_ldac_edge_sel_available" filename="out_voltage10_hw_ldac_edge_sel_available" value="rising_edge falling_edge any_edge" /><attribute name="dither_period_factor" filename="out_voltage10_dither_period_factor" value="128" /><attribute name="dither_period_factor_available" filename="out_voltage10_dither_period_factor_available" value="2 4 8 16 32 64 128" /><attribute name="dither_phase" filename="out_voltage10_dither_phase" value="0" /><attribute name="dither_phase_available" filename="out_voltage10_dither_phase_available" value="0 90 180 270" /><attribute name="ramp_step_size" filename="out_voltage10_ramp_step_size" value="0" /></channel><channel id="voltage11" name="Chn11" type="output"><scan-element index="11" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage11_raw" value="0" /><attribute name="scale" filename="out_voltage11_scale" value="0.0762951076" /><attribute name="offset" filename="out_voltage11_offset" value="0" /><attribute name="input_register_a" filename="out_voltage11_input_register_a" value="0" /><attribute name="input_register_b" filename="out_voltage11_input_register_b" value="0" /><attribute name="output_state" filename="out_voltage11_output_state" value="disable" /><attribute name="output_state_available" filename="out_voltage11_output_state_available" value="disable enable" /><attribute name="range_sel" filename="out_voltage11_range_sel" value="unipolar_5V" /><attribute name="range_sel_available" filename="out_voltage11_range_sel_available" value="unipolar_5V unipolar_10V unipolar_20V unipolar_40V bipolar_5V bipolar_10V bipolar_15V bipolar_20V" /><attribute name="hw_sw_sel" filename="out_voltage11_hw_sw_sel" value="hw" /><attribute name="hw_sw_sel_available" filename="out_voltage11_hw_sw_sel_available" value="hw sw" /><attribute name="func_sel" filename="out_voltage11_func_sel" value="disable" /><attribute name="func_sel_available" filename="out_voltage11_func_sel_available" value="disable ldac_toggle dither sawtooth triangular" /><attribute name="hw_ldac_pin_sel" filename="out_voltage11_hw_ldac_pin_sel" value="ldac_toggle_0" /><attribute name="hw_ldac_pin_sel_available" filename="out_voltage11_hw_ldac_pin_sel_available" value="ldac_toggle_0 ldac_toggle_1 ldac_toggle_2 ldac_toggle_3" /><attribute name="hw_ldac_edge_sel" filename="out_voltage11_hw_ldac_edge_sel" value="rising_edge" /><attribute name="hw_ldac_edge_sel_available" filename="out_voltage11_hw_ldac_edge_sel_available" value="rising_edge falling_edge any_edge" /><attribute name="dither_period_factor" filename="out_voltage11_dither_period_factor" value="128" /><attribute name="dither_period_factor_available" filename="out_voltage11_dither_period_factor_available" value="2 4 8 16 32 64 128" /><attribute name="dither_phase" filename="out_voltage11_dither_phase" value="0" /><attribute name="dither_phase_available" filename="out_voltage11_dither_phase_available" value="0 90 180 270" /><attribute name="ramp_step_size" filename="out_voltage11_ramp_step_size" value="0" /></channel><channel id="voltage12" name="Chn12" type="output"><scan-element index="12" format="le:u16/16>>0" /><attribute name="raw" filename="out_voltage12_raw" va