<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE context [
<!ELEMENT context (device | context-attribute)*>
<!ELEMENT context-attribute EMPTY>
<!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*>
<!ELEMENT channel (scan-element?, attribute*)>
<!ELEMENT attribute EMPTY>
<!ELEMENT scan-element EMPTY>
<!ELEMENT debug-attribute EMPTY>
<!ELEMENT buffer-attribute EMPTY>
<!ATTLIST context name CDATA #REQUIRED description CDATA #IMPLIED>
<!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED>
<!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED>
<!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED>
<!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED>
<!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED value CDATA #IMPLIED>
<!ATTLIST debug-attribute name CDATA #REQUIRED value CDATA #IMPLIED>
<!ATTLIST buffer-attribute name CDATA #REQUIRED value CDATA #IMPLIED>
]>
<context name="local" description="Emulated Context">
    <device id="iio:device0" name="ad7291">
        <channel id="voltage0" type="input">
            <scan-element index="0" format="be:u12/16&gt;&gt;0" />
            <attribute name="raw" value="2048" />
            <attribute name="scale" value="0.610351562" />
        </channel>
        <channel id="voltage1" type="input">
            <scan-element index="1" format="be:u12/16&gt;&gt;0" />
            <attribute name="raw" value="2048" />
            <attribute name="scale" value="0.610351562" />
        </channel>
        <channel id="voltage2" type="input">
            <scan-element index="2" format="be:u12/16&gt;&gt;0" />
            <attribute name="raw" value="2048" />
            <attribute name="scale" value="0.610351562" />
        </channel>
        <channel id="voltage3" type="input">
            <scan-element index="3" format="be:u12/16&gt;&gt;0" />
            <attribute name="raw" value="2048" />
            <attribute name="scale" value="0.610351562" />
        </channel>
        <channel id="voltage4" type="input">
            <scan-element index="4" format="be:u12/16&gt;&gt;0" />
            <attribute name="raw" value="2048" />
            <attribute name="scale" value="0.610351562" />
        </channel>
        <channel id="voltage5" type="input">
            <scan-element index="5" format="be:u12/16&gt;&gt;0" />
            <attribute name="raw" value="2048" />
            <attribute name="scale" value="0.610351562" />
        </channel>
        <channel id="voltage6" type="input">
            <scan-element index="6" format="be:u12/16&gt;&gt;0" />
            <attribute name="raw" value="2048" />
            <attribute name="scale" value="0.610351562" />
        </channel>
        <channel id="voltage7" type="input">
            <scan-element index="7" format="be:u12/16&gt;&gt;0" />
            <attribute name="raw" value="2048" />
            <attribute name="scale" value="0.610351562" />
        </channel>
        <channel id="temp0" type="input">
            <scan-element index="8" format="be:s12/16&gt;&gt;0" />
            <attribute name="mean_raw" value="1000" />
            <attribute name="scale" value="250" />
        </channel>
    </device>
</context>
