<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED value CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED value CDATA #IMPLIED><!ATTLIST buffer-attribute name CDATA #REQUIRED value CDATA #IMPLIED>]><context name="network" description="10.48.65.139 Linux analog 6.6.0-25271-g3917fdd2dbfc-dirty #4 SMP PREEMPT Thu Jan 29 09:51:17 EET 2026 armv7l" ><context-attribute name="hdl_system_id" value="[ada4355_fmc] [BUFMRCE_EN] on [zed] git branch [ada4355_xdc_update] git [5781fd85b80b06cce0cd608f0440a30fd11cabb4] dirty [2025-08-13 05:58:27] UTC" /><context-attribute name="hw_carrier" value="Xilinx Zynq ZED" /><context-attribute name="hw_model" value="EVAL-ADAQ3130FMC1Z on Xilinx Zynq ZED" /><context-attribute name="hw_mezzanine" value="EVAL-ADAQ3130FMC1Z" /><context-attribute name="hw_name" value="ADAQ3130" /><context-attribute name="hw_vendor" value="Analog Devices" /><context-attribute name="hw_serial" value="Empty Field" /><context-attribute name="local,kernel" value="6.6.0-25271-g3917fdd2dbfc-dirty" /><context-attribute name="uri" value="ip:10.48.65.139" /><context-attribute name="ip,ip-addr" value="10.48.65.139" /><device id="hwmon0" name="e000b000ethernetffffffff00" ><channel id="temp1" type="input" ><attribute name="crit" filename="temp1_crit" value="100000" /><attribute name="input" filename="temp1_input" value="36000" /><attribute name="max_alarm" filename="temp1_max_alarm" value="0" /></channel></device><device id="iio:device0" name="ad7291" ><channel id="voltage6" type="input" ><attribute name="raw" filename="in_voltage6_raw" value="2" /><attribute name="scale" filename="in_voltage_scale" value="0.610351562" /></channel><channel id="temp0" type="input" ><attribute name="mean_raw" filename="in_temp0_mean_raw" value="139" /><attribute name="raw" filename="in_temp0_raw" value="137" /><attribute name="scale" filename="in_temp0_scale" value="250" /></channel><channel id="voltage3" type="input" ><attribute name="raw" filename="in_voltage3_raw" value="1666" /><attribute name="scale" filename="in_voltage_scale" value="0.610351562" /></channel><channel id="voltage7" type="input" ><attribute name="raw" filename="in_voltage7_raw" value="2" /><attribute name="scale" filename="in_voltage_scale" value="0.610351562" /></channel><channel id="voltage0" type="input" ><attribute name="raw" filename="in_voltage0_raw" value="2078" /><attribute name="scale" filename="in_voltage_scale" value="0.610351562" /></channel><channel id="voltage4" type="input" ><attribute name="raw" filename="in_voltage4_raw" value="1" /><attribute name="scale" filename="in_voltage_scale" value="0.610351562" /></channel><channel id="voltage1" type="input" ><attribute name="raw" filename="in_voltage1_raw" value="1583" /><attribute name="scale" filename="in_voltage_scale" value="0.610351562" /></channel><channel id="voltage5" type="input" ><attribute name="raw" filename="in_voltage5_raw" value="2" /><attribute name="scale" filename="in_voltage_scale" value="0.610351562" /></channel><channel id="voltage2" type="input" ><attribute name="raw" filename="in_voltage2_raw" value="1820" /><attribute name="scale" filename="in_voltage_scale" value="0.610351562" /></channel><attribute name="waiting_for_supplier" value="0" /></device><device id="iio:device2" name="ada4355" ><channel id="voltage0" type="input" ><scan-element index="0" format="le:s14/16&gt;&gt;2" scale="0.000122" /><attribute name="scale" filename="in_voltage0_scale" value="0.000122070" /></channel><attribute name="sampling_frequency" value="125000000" /><attribute name="sync_start_enable" value="disarm" /><attribute name="sync_start_enable_available" value="arm" /><attribute name="waiting_for_supplier" value="0" /><buffer-attribute name="data_available" value="0" /><buffer-attribute name="direction" value="in" /><buffer-attribute name="length_align_bytes" value="8" /><debug-attribute name="pseudorandom_err_check" value="CH0 : PN9 : In Sync : PN Error" /><debug-attribute name="direct_reg_access" value="0x18" /></device><device id="iio:device3" name="xadc" ><channel id="voltage5" name="vccoddr" type="input" ><attribute name="label" filename="in_voltage5_vccoddr_label" value="vccoddr" /><attribute name="raw" filename="in_voltage5_vccoddr_raw" value="2040" /><attribute name="scale" filename="in_voltage5_vccoddr_scale" value="0.732421875" /></channel><channel id="voltage0" name="vccint" type="input" ><attribute name="label" filename="in_voltage0_vccint_label" value="vccint" /><attribute name="raw" filename="in_voltage0_vccint_raw" value="1351" /><attribute name="scale" filename="in_voltage0_vccint_scale" value="0.732421875" /></channel><channel id="voltage4" name="vccpaux" type="input" ><attribute name="label" filename="in_voltage4_vccpaux_label" value="vccpaux" /><attribute name="raw" filename="in_voltage4_vccpaux_raw" value="2453" /><attribute name="scale" filename="in_voltage4_vccpaux_scale" value="0.732421875" /></channel><channel id="temp0" type="input" ><attribute name="offset" filename="in_temp0_offset" value="-2219" /><attribute name="raw" filename="in_temp0_raw" value="2617" /><attribute name="scale" filename="in_temp0_scale" value="123.040771484" /></channel><channel id="voltage7" name="vrefn" type="input" ><attribute name="label" filename="in_voltage7_vrefn_label" value="vrefn" /><attribute name="raw" filename="in_voltage7_vrefn_raw" value="-2" /><attribute name="scale" filename="in_voltage7_vrefn_scale" value="0.732421875" /></channel><channel id="voltage1" name="vccaux" type="input" ><attribute name="label" filename="in_voltage1_vccaux_label" value="vccaux" /><attribute name="raw" filename="in_voltage1_vccaux_raw" value="2462" /><attribute name="scale" filename="in_voltage1_vccaux_scale" value="0.732421875" /></channel><channel id="voltage2" name="vccbram" type="input" ><attribute name="label" filename="in_voltage2_vccbram_label" value="vccbram" /><attribute name="raw" filename="in_voltage2_vccbram_raw" value="1349" /><attribute name="scale" filename="in_voltage2_vccbram_scale" value="0.732421875" /></channel><channel id="voltage3" name="vccpint" type="input" ><attribute name="label" filename="in_voltage3_vccpint_label" value="vccpint" /><attribute name="raw" filename="in_voltage3_vccpint_raw" value="1346" /><attribute name="scale" filename="in_voltage3_vccpint_scale" value="0.732421875" /></channel><channel id="voltage6" name="vrefp" type="input" ><attribute name="label" filename="in_voltage6_vrefp_label" value="vrefp" /><attribute name="raw" filename="in_voltage6_vrefp_raw" value="1702" /><attribute name="scale" filename="in_voltage6_vrefp_scale" value="0.732421875" /></channel><attribute name="sampling_frequency" value="961538" /><attribute name="waiting_for_supplier" value="0" /></device><device id="iio:device4" name="one-bit-adc-dac" ><channel id="voltage1" type="output" ><attribute name="label" filename="out_voltage1_label" value="GSEL1" /><attribute name="raw" filename="out_voltage1_raw" value="0" /></channel><channel id="voltage5" type="output" ><attribute name="label" filename="out_voltage5_label" value="GSEL3" /><attribute name="raw" filename="out_voltage5_raw" value="0" /></channel><channel id="voltage0" type="output" ><attribute name="label" filename="out_voltage0_label" value="GSEL0" /><attribute name="raw" filename="out_voltage0_raw" value="0" /></channel><channel id="voltage3" type="output" ><attribute name="label" filename="out_voltage3_label" value="GSEL2" /><attribute name="raw" filename="out_voltage3_raw" value="0" /></channel><channel id="voltage6" type="output" ><attribute name="label" filename="out_voltage6_label" value="FSEL1" /><attribute name="raw" filename="out_voltage6_raw" value="0" /></channel><channel id="voltage2" type="output" ><attribute name="label" filename="out_voltage2_label" value="FSEL0" /><attribute name="raw" filename="out_voltage2_raw" value="0" /></channel><channel id="voltage4" type="output" ><attribute name="label" filename="out_voltage4_label" value="GPIO_TEST" /><attribute name="raw" filename="out_voltage4_raw" value="0" /></channel><attribute name="waiting_for_supplier" value="0" /></device><device id="iio:device5" name="adi-iio-fakedev" ><channel id="channel2" type="output" ><attribute name="enable" filename="out_channel2_enable" value="0" /><attribute name="off_ms" filename="out_channel2_off_ms" value="0.000000" /><attribute name="off_raw" filename="out_channel2_off_raw" value="0" /><attribute name="on_ms" filename="out_channel2_on_ms" value="0.000000" /><attribute name="on_raw" filename="out_channel2_on_raw" value="0" /><attribute name="polarity" filename="out_channel2_polarity" value="0" /></channel><channel id="channel0" type="output" ><attribute name="enable" filename="out_channel0_enable" value="1" /><attribute name="off_ms" filename="out_channel0_off_ms" value="0.001080" /><attribute name="off_raw" filename="out_channel0_off_raw" value="135" /><attribute name="on_ms" filename="out_channel0_on_ms" value="0.000080" /><attribute name="on_raw" filename="out_channel0_on_raw" value="10" /><attribute name="polarity" filename="out_channel0_polarity" value="0" /></channel><channel id="channel1" type="output" ><attribute name="enable" filename="out_channel1_enable" value="1" /><attribute name="off_ms" filename="out_channel1_off_ms" value="0.020000" /><attribute name="off_raw" filename="out_channel1_off_raw" value="2500" /><attribute name="on_ms" filename="out_channel1_on_ms" value="0.000000" /><attribute name="on_raw" filename="out_channel1_on_raw" value="0" /><attribute name="polarity" filename="out_channel1_polarity" value="0" /></channel><attribute name="burst_count" value="0" /><attribute name="core_id" value="0" /><attribute name="enable" value="1" /><attribute name="frame_length_ms" value="0.100008" /><attribute name="frame_length_raw" value="12500" /><attribute name="internal_sync_period_ms" value="0.000000" /><attribute name="internal_sync_period_raw" value="0" /><attribute name="magic" value="0x5444444e" /><attribute name="scratch" value="0x00000000" /><attribute name="startup_delay_ms" value="0.000000" /><attribute name="startup_delay_raw" value="0" /><attribute name="state" value="3" /><attribute name="sync_external" value="0" /><attribute name="sync_internal" value="0" /><attribute name="sync_reset" value="0" /><attribute name="sync_soft" value="ERROR" /><attribute name="version" value="2.00.b" /><attribute name="waiting_for_supplier" value="0" /></device><device id="iio_sysfs_trigger" ><attribute name="add_trigger" value="ERROR" /><attribute name="remove_trigger" value="ERROR" /></device></context>
