<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED version-major CDATA #REQUIRED version-minor CDATA #REQUIRED version-git CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED label CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED><!ATTLIST buffer-attribute name CDATA #REQUIRED>]><context name="xml" version-major="0" version-minor="25" version-git="5e7f76e" description="Linux analog 6.17.0-rc3-iio-zed-new+ #114 SMP PREEMPT Mon Oct  6 13:59:42 -03 2025 armv7l" ><context-attribute name="hw_model" value="EVAL-ADAQ4216-FMCZ on Xilinx Zynq ZED" /><context-attribute name="hw_carrier" value="Xilinx Zynq ZED" /><context-attribute name="local,kernel" value="6.17.0-rc3-iio-zed-new+" /><context-attribute name="uri" value="local:" /><device id="hwmon0" name="e000b000ethernetffffffff00" ><channel id="temp1" type="input" ><attribute name="crit" filename="temp1_crit" /><attribute name="input" filename="temp1_input" /><attribute name="max_alarm" filename="temp1_max_alarm" /></channel></device><device id="iio:device0" name="adaq4216" ><channel id="voltage0-voltage1" type="input" ><scan-element index="0" format="le:s16/32&gt;&gt;0" scale="0.018750" /><attribute name="calibbias" filename="in_voltage0-voltage1_calibbias" /><attribute name="calibbias_available" filename="in_voltage0-voltage1_calibbias_available" /><attribute name="calibscale" filename="in_voltage0-voltage1_calibscale" /><attribute name="calibscale_available" filename="in_voltage0-voltage1_calibscale_available" /><attribute name="label" filename="in_voltage0-voltage1_label" /><attribute name="raw" filename="in_voltage0-voltage1_raw" /><attribute name="scale" filename="in_voltage0-voltage1_scale" /><attribute name="scale_available" filename="in_voltage0-voltage1_scale_available" /></channel><channel id="voltage2" type="input" ><scan-element index="1" format="be:U8/8&gt;&gt;0" scale="16.000000" /><attribute name="label" filename="in_voltage2_label" /><attribute name="raw" filename="in_voltage2_raw" /><attribute name="scale" filename="in_voltage2_scale" /></channel><attribute name="oversampling_ratio" /><attribute name="oversampling_ratio_available" /><attribute name="sampling_frequency" /><attribute name="waiting_for_supplier" /><buffer-attribute name="data_available" /><buffer-attribute name="direction" /><buffer-attribute name="length_align_bytes" /><debug-attribute name="direct_reg_access" /></device><device id="iio_sysfs_trigger" ><attribute name="add_trigger" /><attribute name="remove_trigger" /></device></context>
