<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE context [
  <!ELEMENT context (device | context-attribute)*>
  <!ELEMENT context-attribute EMPTY>
  <!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*>
  <!ELEMENT channel (scan-element?, attribute*)>
  <!ELEMENT attribute EMPTY>
  <!ELEMENT scan-element EMPTY>
  <!ELEMENT debug-attribute EMPTY>
  <!ELEMENT buffer-attribute EMPTY>
  <!ATTLIST context name CDATA #REQUIRED description CDATA #IMPLIED>
  <!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED>
  <!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED>
  <!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED>
  <!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED>
  <!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED value CDATA #IMPLIED>
  <!ATTLIST debug-attribute name CDATA #REQUIRED value CDATA #IMPLIED>
  <!ATTLIST buffer-attribute name CDATA #REQUIRED value CDATA #IMPLIED>
]>
<context name="serial" description="no-OS/projects/admt4000 staging/admt4000-d14c4e93f">
  <context-attribute name="fw_version" value="v1.0.0-a.0" />
  <context-attribute name="hw_carrier" value="SDP_K1" />
  <context-attribute name="hw_mezzanine_status" value="not_detected" />
  <context-attribute name="uri" value="serial:COM10,230400,8n1n" />
  <context-attribute name="serial,port" value="COM10" />
  <context-attribute name="serial,description" value="USB Serial Device (COM10)" />
  <device id="iio:device0" name="admt_evb">
    <attribute name="pulse_shutdown" value="1" />
    <attribute name="power_enable" value="ERROR" />
    <attribute name="coil_reset" value="537198000" />
  </device>
  <device id="iio:device1" name="admt4000">
    <channel id="rot" name="turns" type="input">
      <scan-element index="0" format="le:s8/16&gt;&gt;0" />
      <attribute name="raw" filename="in_rot_raw" value="66" />
      <attribute name="scale" filename="in_rot_scale" value="0.250000000" />
    </channel>
    <channel id="angl" name="angle" type="input">
      <scan-element index="1" format="le:u12/16&gt;&gt;0" />
      <attribute name="raw" filename="in_angl_raw" value="2121" />
      <attribute name="scale" filename="in_angl_scale" value="0.087890625" />
    </channel>
    <channel id="temp" name="temp" type="input">
      <scan-element index="2" format="le:u12/16&gt;&gt;0" />
      <attribute name="raw" filename="in_temp_raw" value="1933" />
      <attribute name="scale" filename="in_temp_scale" value="63.856960408" />
      <attribute name="offset" filename="in_temp_offset" value="1168" />
    </channel>
    <channel id="count1" name="cosine" type="input">
      <scan-element index="3" format="le:s14/16&gt;&gt;0" />
      <attribute name="raw" filename="in_count1_raw" value="3524" />
    </channel>
    <channel id="count2" name="sine" type="input">
      <scan-element index="4" format="le:s14/16&gt;&gt;0" />
      <attribute name="raw" filename="in_count2_raw" value="862" />
    </channel>
    <channel id="voltage" name="radius" type="input">
      <scan-element index="5" format="le:u15/16&gt;&gt;0" />
      <attribute name="raw" filename="in_voltage_raw" value="11978" />
      <attribute name="scale" filename="in_voltage_scale" value="0.000924000" />
    </channel>
    <attribute name="conv_sync_mode" value="seq_ctrl" />
    <attribute name="conv_sync_mode_available" value="seq_ctrl   start_edge " />
    <attribute name="angle_filter_enable" value="1" />
    <attribute name="conversion_mode" value="0" />
    <attribute name="h8_corr_src" value="factory" />
    <attribute name="h8_corr_src_available" value="factory user " />
    <attribute name="harmonics" value="0 0 0 0 0 0 0 0" />
    <attribute name="harmonics_magnitude_scale" value="0.009046" />
    <attribute name="harmonics_phase_scale" value="0.087891" />
    <attribute name="faults" value="0" />
    <attribute name="reinitialize" value="ERROR" />
    <attribute name="gpio0_raw" value="0" />
    <attribute name="gpio1_raw" value="0" />
    <attribute name="gpio2_raw" value="0" />
    <attribute name="gpio3_raw" value="0" />
    <attribute name="gpio4_raw" value="0" />
    <attribute name="gpio5_raw" value="1" />
    <debug-attribute name="reset" value="ERROR" />
    <debug-attribute name="direct_reg_access" value="0" />
  </device>
  <device id="trigger0" name="admt4000-dev0" />
</context>
