<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED value CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED value CDATA #IMPLIED><!ATTLIST buffer-attribute name CDATA #REQUIRED value CDATA #IMPLIED>]><context name="network" description="192.168.10.107 Linux analog 5.15.0-175828-g0a3ef1dba842 #4436 SMP PREEMPT Tue Aug 1 06:45:40 IST 2023 armv7l" ><context-attribute name="hdl_system_id" value="[adrv9001] on [zed] git branch [master] git [ea29a37eae8a1daeaadb79281b3085709aaedb1c] clean [2023-07-26 06:22:31] UTC" /><context-attribute name="hw_model" value="ADRV9002NP/W1/PCBZ on Xilinx Zynq ZED" /><context-attribute name="hw_carrier" value="Xilinx Zynq ZED" /><context-attribute name="hw_mezzanine" value="ADRV9002NP/W1/PCBZ" /><context-attribute name="hw_name" value="ADRV9001 Cust.EVB" /><context-attribute name="hw_vendor" value="Analog Devices" /><context-attribute name="hw_serial" value="07500127" /><context-attribute name="local,kernel" value="5.15.0-175828-g0a3ef1dba842" /><context-attribute name="uri" value="ip:192.168.10.107" /><context-attribute name="ip,ip-addr" value="192.168.10.107" /><device id="hwmon0" name="e000b000ethernetffffffff00" ><channel id="temp1" type="input" ><attribute name="crit" filename="temp1_crit" value="100000" /><attribute name="input" filename="temp1_input" value="44000" /><attribute name="max_alarm" filename="temp1_max_alarm" value="0" /></channel></device><device id="iio:device0" name="adrv9002-phy" ><channel id="voltage0" type="input" ><attribute name="agc_tracking_en" filename="in_voltage0_agc_tracking_en" value="1" /><attribute name="bbdc_loop_gain_raw" filename="in_voltage0_bbdc_loop_gain_raw" value="1048576" /><attribute name="bbdc_rejection_en" filename="in_voltage0_bbdc_rejection_en" value="1" /><attribute name="bbdc_rejection_tracking_en" filename="in_voltage0_bbdc_rejection_tracking_en" value="1" /><attribute name="decimated_power" filename="in_voltage0_decimated_power" value="12.750 dB" /><attribute name="digital_gain_control_mode" filename="in_voltage0_digital_gain_control_mode" value="spi" /><attribute name="digital_gain_control_mode_available" filename="in_voltage0_digital_gain_control_mode_available" value="automatic spi" /><attribute name="dynamic_adc_switch_en" filename="in_voltage0_dynamic_adc_switch_en" value="0" /><attribute name="en" filename="in_voltage0_en" value="1" /><attribute name="ensm_mode" filename="in_voltage0_ensm_mode" value="rf_enabled" /><attribute name="ensm_mode_available" filename="in_voltage0_ensm_mode_available" value="calibrated primed rf_enabled" /><attribute name="gain_control_mode" filename="in_voltage0_gain_control_mode" value="spi" /><attribute name="gain_control_mode_available" filename="in_voltage0_gain_control_mode_available" value="spi pin automatic" /><attribute name="hardwaregain" filename="in_voltage0_hardwaregain" value="34.000000 dB" /><attribute name="hd_tracking_en" filename="in_voltage0_hd_tracking_en" value="0" /><attribute name="interface_gain" filename="in_voltage0_interface_gain" value="0dB" /><attribute name="interface_gain_available" filename="in_voltage0_interface_gain_available" value="0dB" /><attribute name="nco_frequency" filename="in_voltage0_nco_frequency" value="0" /><attribute name="orx_bbdc_rejection_en" filename="in_voltage0_orx_bbdc_rejection_en" value="ERROR" /><attribute name="orx_en" filename="in_voltage0_orx_en" value="ERROR" /><attribute name="orx_hardwaregain" filename="in_voltage0_orx_hardwaregain" value="ERROR" /><attribute name="orx_label" filename="in_voltage0_orx_label" value="orx" /><attribute name="orx_quadrature_w_poly_tracking_en" filename="in_voltage0_orx_quadrature_w_poly_tracking_en" value="ERROR" /><attribute name="port_en_mode" filename="in_voltage0_port_en_mode" value="spi" /><attribute name="port_en_mode_available" filename="in_voltage0_port_en_mode_available" value="spi pin" /><attribute name="quadrature_fic_tracking_en" filename="in_voltage0_quadrature_fic_tracking_en" value="1" /><attribute name="quadrature_w_poly_tracking_en" filename="in_voltage0_quadrature_w_poly_tracking_en" value="0" /><attribute name="rf_bandwidth" filename="in_voltage0_rf_bandwidth" value="1008000" /><attribute name="rfdc_tracking_en" filename="in_voltage0_rfdc_tracking_en" value="1" /><attribute name="rssi" filename="in_voltage0_rssi" value="81.875 dB" /><attribute name="rssi_tracking_en" filename="in_voltage0_rssi_tracking_en" value="1" /><attribute name="sampling_frequency" filename="in_voltage0_sampling_frequency" value="1920000" /></channel><channel id="voltage1" type="input" ><attribute name="agc_tracking_en" filename="in_voltage1_agc_tracking_en" value="1" /><attribute name="bbdc_loop_gain_raw" filename="in_voltage1_bbdc_loop_gain_raw" value="1048576" /><attribute name="bbdc_rejection_en" filename="in_voltage1_bbdc_rejection_en" value="1" /><attribute name="bbdc_rejection_tracking_en" filename="in_voltage1_bbdc_rejection_tracking_en" value="1" /><attribute name="decimated_power" filename="in_voltage1_decimated_power" value="12.500 dB" /><attribute name="digital_gain_control_mode" filename="in_voltage1_digital_gain_control_mode" value="spi" /><attribute name="digital_gain_control_mode_available" filename="in_voltage1_digital_gain_control_mode_available" value="automatic spi" /><attribute name="dynamic_adc_switch_en" filename="in_voltage1_dynamic_adc_switch_en" value="0" /><attribute name="en" filename="in_voltage1_en" value="1" /><attribute name="ensm_mode" filename="in_voltage1_ensm_mode" value="rf_enabled" /><attribute name="ensm_mode_available" filename="in_voltage1_ensm_mode_available" value="calibrated primed rf_enabled" /><attribute name="gain_control_mode" filename="in_voltage1_gain_control_mode" value="spi" /><attribute name="gain_control_mode_available" filename="in_voltage1_gain_control_mode_available" value="spi pin automatic" /><attribute name="hardwaregain" filename="in_voltage1_hardwaregain" value="34.000000 dB" /><attribute name="hd_tracking_en" filename="in_voltage1_hd_tracking_en" value="0" /><attribute name="interface_gain" filename="in_voltage1_interface_gain" value="0dB" /><attribute name="interface_gain_available" filename="in_voltage1_interface_gain_available" value="0dB" /><attribute name="nco_frequency" filename="in_voltage1_nco_frequency" value="0" /><attribute name="orx_bbdc_rejection_en" filename="in_voltage1_orx_bbdc_rejection_en" value="ERROR" /><attribute name="orx_en" filename="in_voltage1_orx_en" value="ERROR" /><attribute name="orx_hardwaregain" filename="in_voltage1_orx_hardwaregain" value="ERROR" /><attribute name="orx_label" filename="in_voltage1_orx_label" value="orx" /><attribute name="orx_quadrature_w_poly_tracking_en" filename="in_voltage1_orx_quadrature_w_poly_tracking_en" value="ERROR" /><attribute name="port_en_mode" filename="in_voltage1_port_en_mode" value="spi" /><attribute name="port_en_mode_available" filename="in_voltage1_port_en_mode_available" value="spi pin" /><attribute name="quadrature_fic_tracking_en" filename="in_voltage1_quadrature_fic_tracking_en" value="1" /><attribute name="quadrature_w_poly_tracking_en" filename="in_voltage1_quadrature_w_poly_tracking_en" value="0" /><attribute name="rf_bandwidth" filename="in_voltage1_rf_bandwidth" value="1008000" /><attribute name="rfdc_tracking_en" filename="in_voltage1_rfdc_tracking_en" value="1" /><attribute name="rssi" filename="in_voltage1_rssi" value="83.316 dB" /><attribute name="rssi_tracking_en" filename="in_voltage1_rssi_tracking_en" value="1" /><attribute name="sampling_frequency" filename="in_voltage1_sampling_frequency" value="1920000" /></channel><channel id="voltage1" type="output" ><attribute name="atten_control_mode" filename="out_voltage1_atten_control_mode" value="spi" /><attribute name="atten_control_mode_available" filename="out_voltage1_atten_control_mode_available" value="bypass spi pin" /><attribute name="close_loop_gain_tracking_en" filename="out_voltage1_close_loop_gain_tracking_en" value="0" /><attribute name="en" filename="out_voltage1_en" value="1" /><attribute name="ensm_mode" filename="out_voltage1_ensm_mode" value="rf_enabled" /><attribute name="ensm_mode_available" filename="out_voltage1_ensm_mode_available" value="calibrated primed rf_enabled" /><attribute name="hardwaregain" filename="out_voltage1_hardwaregain" value="-10.000000 dB" /><attribute name="lo_leakage_tracking_en" filename="out_voltage1_lo_leakage_tracking_en" value="0" /><attribute name="loopback_delay_tracking_en" filename="out_voltage1_loopback_delay_tracking_en" value="0" /><attribute name="nco_frequency" filename="out_voltage1_nco_frequency" value="0" /><attribute name="pa_correction_tracking_en" filename="out_voltage1_pa_correction_tracking_en" value="0" /><attribute name="port_en_mode" filename="out_voltage1_port_en_mode" value="spi" /><attribute name="port_en_mode_available" filename="out_voltage1_port_en_mode_available" value="spi pin" /><attribute name="quadrature_tracking_en" filename="out_voltage1_quadrature_tracking_en" value="0" /><attribute name="rf_bandwidth" filename="out_voltage1_rf_bandwidth" value="1008000" /><attribute name="sampling_frequency" filename="out_voltage1_sampling_frequency" value="1920000" /></channel><channel id="voltage0" type="output" ><attribute name="atten_control_mode" filename="out_voltage0_atten_control_mode" value="spi" /><attribute name="atten_control_mode_available" filename="out_voltage0_atten_control_mode_available" value="bypass spi pin" /><attribute name="close_loop_gain_tracking_en" filename="out_voltage0_close_loop_gain_tracking_en" value="0" /><attribute name="en" filename="out_voltage0_en" value="1" /><attribute name="ensm_mode" filename="out_voltage0_ensm_mode" value="rf_enabled" /><attribute name="ensm_mode_available" filename="out_voltage0_ensm_mode_available" value="calibrated primed rf_enabled" /><attribute name="hardwaregain" filename="out_voltage0_hardwaregain" value="-10.000000 dB" /><attribute name="lo_leakage_tracking_en" filename="out_voltage0_lo_leakage_tracking_en" value="0" /><attribute name="loopback_delay_tracking_en" filename="out_voltage0_loopback_delay_tracking_en" value="0" /><attribute name="nco_frequency" filename="out_voltage0_nco_frequency" value="0" /><attribute name="pa_correction_tracking_en" filename="out_voltage0_pa_correction_tracking_en" value="0" /><attribute name="port_en_mode" filename="out_voltage0_port_en_mode" value="spi" /><attribute name="port_en_mode_available" filename="out_voltage0_port_en_mode_available" value="spi pin" /><attribute name="quadrature_tracking_en" filename="out_voltage0_quadrature_tracking_en" value="0" /><attribute name="rf_bandwidth" filename="out_voltage0_rf_bandwidth" value="1008000" /><attribute name="sampling_frequency" filename="out_voltage0_sampling_frequency" value="1920000" /></channel><channel id="voltage2" type="input" ><attribute name="en" filename="in_voltage2_en" value="0" /><attribute name="input" filename="in_voltage2_input" value="0" /></channel><channel id="altvoltage0" name="RX1_LO" type="output" ><attribute name="frequency" filename="out_altvoltage0_RX1_LO_frequency" value="2400000000" /><attribute name="label" filename="out_altvoltage0_RX1_LO_label" value="RX1_LO" /></channel><channel id="voltage5" type="input" ><attribute name="en" filename="in_voltage5_en" value="0" /><attribute name="input" filename="in_voltage5_input" value="0" /></channel><channel id="altvoltage3" name="TX2_LO" type="output" ><attribute name="frequency" filename="out_altvoltage3_TX2_LO_frequency" value="2450000000" /><attribute name="label" filename="out_altvoltage3_TX2_LO_label" value="TX2_LO" /></channel><channel id="voltage3" type="output" ><attribute name="en" filename="out_voltage3_en" value="0" /><attribute name="input" filename="out_voltage3_input" value="50" /></channel><channel id="voltage2" type="output" ><attribute name="en" filename="out_voltage2_en" value="0" /><attribute name="input" filename="out_voltage2_input" value="50" /></channel><channel id="voltage5" type="output" ><attribute name="en" filename="out_voltage5_en" value="0" /><attribute name="input" filename="out_voltage5_input" value="50" /></channel><channel id="voltage4" type="input" ><attribute name="en" filename="in_voltage4_en" value="0" /><attribute name="input" filename="in_voltage4_input" value="0" /></channel><channel id="altvoltage1" name="RX2_LO" type="output" ><attribute name="frequency" filename="out_altvoltage1_RX2_LO_frequency" value="2400000000" /><attribute name="label" filename="out_altvoltage1_RX2_LO_label" value="RX2_LO" /></channel><channel id="temp0" type="input" ><attribute name="input" filename="in_temp0_input" value="68000" /></channel><channel id="voltage3" type="input" ><attribute name="en" filename="in_voltage3_en" value="0" /><attribute name="input" filename="in_voltage3_input" value="0" /></channel><channel id="altvoltage2" name="TX1_LO" type="output" ><attribute name="frequency" filename="out_altvoltage2_TX1_LO_frequency" value="2450000000" /><attribute name="label" filename="out_altvoltage2_TX1_LO_label" value="TX1_LO" /></channel><channel id="voltage4" type="output" ><attribute name="en" filename="out_voltage4_en" value="0" /><attribute name="input" filename="out_voltage4_input" value="50" /></channel><attribute name="frequency_hopping_hop1_signal_trigger" value="ERROR" /><attribute name="frequency_hopping_hop1_table_a" value="ERROR" /><attribute name="frequency_hopping_hop1_table_b" value="ERROR" /><attribute name="frequency_hopping_hop1_table_select" value="ERROR" /><attribute name="frequency_hopping_hop2_signal_trigger" value="ERROR" /><attribute name="frequency_hopping_hop2_table_a" value="ERROR" /><attribute name="frequency_hopping_hop2_table_b" value="ERROR" /><attribute name="frequency_hopping_hop2_table_select" value="ERROR" /><attribute name="frequency_hopping_hop_table_select_available" value="TABLE_A TABLE_B" /><attribute name="profile_config" value="ERROR" /><attribute name="stream_config" value="ERROR" /><debug-attribute name="agpio11_direction" value="0" /><debug-attribute name="agpio11_value" value="0" /><debug-attribute name="agpio10_direction" value="0" /><debug-attribute name="agpio10_value" value="0" /><debug-attribute name="agpio9_direction" value="0" /><debug-attribute name="agpio9_value" value="0" /><debug-attribute name="agpio8_direction" value="0" /><debug-attribute name="agpio8_value" value="0" /><debug-attribute name="agpio7_direction" value="0" /><debug-attribute name="agpio7_value" value="0" /><debug-attribute name="agpio6_direction" value="0" /><debug-attribute name="agpio6_value" value="0" /><debug-attribute name="agpio5_direction" value="0" /><debug-attribute name="agpio5_value" value="0" /><debug-attribute name="agpio4_direction" value="0" /><debug-attribute name="agpio4_value" value="0" /><debug-attribute name="agpio3_direction" value="0" /><debug-attribute name="agpio3_value" value="0" /><debug-attribute name="agpio2_direction" value="0" /><debug-attribute name="agpio2_value" value="0" /><debug-attribute name="agpio1_direction" value="0" /><debug-attribute name="agpio1_value" value="0" /><debug-attribute name="agpio0_direction" value="0" /><debug-attribute name="agpio0_value" value="0" /><debug-attribute name="dgpio15_direction" value="0" /><debug-attribute name="dgpio15_value" value="0" /><debug-attribute name="dgpio14_direction" value="0" /><debug-attribute name="dgpio14_value" value="0" /><debug-attribute name="dgpio13_direction" value="0" /><debug-attribute name="dgpio13_value" value="0" /><debug-attribute name="dgpio12_direction" value="0" /><debug-attribute name="dgpio12_value" value="0" /><debug-attribute name="dgpio11_direction" value="0" /><debug-attribute name="dgpio11_value" value="0" /><debug-attribute name="dgpio10_direction" value="0" /><debug-attribute name="dgpio10_value" value="0" /><debug-attribute name="dgpio9_direction" value="0" /><debug-attribute name="dgpio9_value" value="1" /><debug-attribute name="dgpio8_direction" value="0" /><debug-attribute name="dgpio8_value" value="0" /><debug-attribute name="dgpio7_direction" value="0" /><debug-attribute name="dgpio7_value" value="0" /><debug-attribute name="dgpio6_direction" value="0" /><debug-attribute name="dgpio6_value" value="0" /><debug-attribute name="dgpio5_direction" value="0" /><debug-attribute name="dgpio5_value" value="0" /><debug-attribute name="dgpio4_direction" value="0" /><debug-attribute name="dgpio4_value" value="0" /><debug-attribute name="dgpio3_direction" value="0" /><debug-attribute name="dgpio3_value" value="0" /><debug-attribute name="dgpio2_direction" value="0" /><debug-attribute name="dgpio2_value" value="1" /><debug-attribute name="dgpio1_direction" value="0" /><debug-attribute name="dgpio1_value" value="0" /><debug-attribute name="dgpio0_direction" value="0" /><debug-attribute name="dgpio0_value" value="0" /><debug-attribute name="fh_config_dump" value="ERROR" /><debug-attribute name="fh_tx1_port_hop_signal" value="1" /><debug-attribute name="fh_rx1_port_hop_signal" value="1" /><debug-attribute name="fh_tx0_port_hop_signal" value="0" /><debug-attribute name="fh_rx0_port_hop_signal" value="0" /><debug-attribute name="fh_hop2_table_b_dump" value="ERROR" /><debug-attribute name="fh_hop2_table_a_dump" value="ERROR" /><debug-attribute name="fh_hop2_table_select_pin_set" value="0" /><debug-attribute name="fh_hop2_pin_set" value="0" /><debug-attribute name="fh_hop1_table_b_dump" value="ERROR" /><debug-attribute name="fh_hop1_table_a_dump" value="ERROR" /><debug-attribute name="fh_hop1_table_select_pin_set" value="0" /><debug-attribute name="fh_hop1_pin_set" value="0" /><debug-attribute name="fh_hop_table_mode_select" value="0" /><debug-attribute name="fh_table_index_control_pin6" value="0" /><debug-attribute name="fh_table_index_control_pin5" value="0" /><debug-attribute name="fh_table_index_control_pin4" value="0" /><debug-attribute name="fh_table_index_control_pin3" value="0" /><debug-attribute name="fh_table_index_control_pin2" value="0" /><debug-attribute name="fh_table_index_control_pin1" value="0" /><debug-attribute name="fh_table_index_control_npins" value="0" /><debug-attribute name="fh_table_index_control_mode" value="0" /><debug-attribute name="fh_max_lo_freq_hz" value="6000000000" /><debug-attribute name="fh_min_lo_freq_hz" value="25000000" /><debug-attribute name="fh_min_frame_duration_us" value="0" /><debug-attribute name="fh_mode" value="3" /><debug-attribute name="fh_max_tx_atten_mdb" value="41950" /><debug-attribute name="fh_min_tx_atten_mdb" value="0" /><debug-attribute name="fh_rx_zero_if_en" value="Y" /><debug-attribute name="fh_tx_analog_power_on_frame_delay" value="0" /><debug-attribute name="fh_max_rx_gain" value="255" /><debug-attribute name="fh_min_rx_gain" value="187" /><debug-attribute name="rx1_near_end_loopback" value="ERROR" /><debug-attribute name="rx1_enablement_delays" value="fall_to_off_delay: 0
guard_delay: 0
hold_delay: 0
rise_to_analog_on_delay: 0
rise_to_on_delay: 0" /><debug-attribute name="rx1_rise_to_on_delay_ns" value="0" /><debug-attribute name="rx1_rise_to_analog_delay_ns" value="0" /><debug-attribute name="rx1_hold_delay_ns" value="0" /><debug-attribute name="rx1_guard_delay_ns" value="0" /><debug-attribute name="rx1_fall_to_off_delay_ns" value="0" /><debug-attribute name="rx1_ssi_q_data_delay" value="0" /><debug-attribute name="rx1_ssi_i_data_delay" value="0" /><debug-attribute name="rx1_ssi_strobe_delay" value="0" /><debug-attribute name="rx1_ssi_clk_delay" value="0" /><debug-attribute name="rx1_agc_peak.feedback_apd_high_hb_high" value="0" /><debug-attribute name="rx1_agc_peak.feedback_apd_low_hb_low" value="0" /><debug-attribute name="rx1_agc_peak.hbUnderRangeLowThreshExceededCount" value="3" /><debug-attribute name="rx1_agc_peak.hbUnderRangeMidThreshExceededCount" value="3" /><debug-attribute name="rx1_agc_peak.hbOverloadPowerMode" value="0" /><debug-attribute name="rx1_agc_peak.hbGainStepAttack" value="2" /><debug-attribute name="rx1_agc_peak.hbGainStepMidRecovery" value="4" /><debug-attribute name="rx1_agc_peak.hbGainStepLowRecovery" value="6" /><debug-attribute name="rx1_agc_peak.hbGainStepHighRecovery" value="2" /><debug-attribute name="rx1_agc_peak.hbUnderRangeHighThreshExceededCount" value="3" /><debug-attribute name="rx1_agc_peak.hbUpperThreshPeakExceededCount" value="6" /><debug-attribute name="rx1_agc_peak.hbUnderRangeHighThresh" value="7335" /><debug-attribute name="rx1_agc_peak.hbUnderRangeMidThresh" value="8230" /><debug-attribute name="rx1_agc_peak.hbUnderRangeLowThresh" value="5826" /><debug-attribute name="rx1_agc_peak.hbHighThresh" value="13044" /><debug-attribute name="rx1_agc_peak.hbOverloadThreshCount" value="1" /><debug-attribute name="rx1_agc_peak.hbOverloadDurationCount" value="1" /><debug-attribute name="rx1_agc_peak.enableHbOverload" value="Y" /><debug-attribute name="rx1_agc_peak.apdGainStepRecovery" value="0" /><debug-attribute name="rx1_agc_peak.apdGainStepAttack" value="2" /><debug-attribute name="rx1_agc_peak.apdLowerThreshPeakExceededCount" value="3" /><debug-attribute name="rx1_agc_peak.apdUpperThreshPeakExceededCount" value="6" /><debug-attribute name="rx1_agc_peak.apdLowThresh" value="12" /><debug-attribute name="rx1_agc_peak.apdHighThresh" value="21" /><debug-attribute name="rx1_agc_peak.agcUnderRangeHighInterval" value="4" /><debug-attribute name="rx1_agc_peak.agcUnderRangeMidInterval" value="2" /><debug-attribute name="rx1_agc_peak.agcUnderRangeLowInterval" value="50" /><debug-attribute name="rx1_agc_power.feedback_apd_high_apd_low" value="0" /><debug-attribute name="rx1_agc_power.feedback_inner_high_inner_low" value="0" /><debug-attribute name="rx1_agc_power.overRangeLowPowerGainStepAttack" value="4" /><debug-attribute name="rx1_agc_power.overRangeHighPowerGainStepAttack" value="4" /><debug-attribute name="rx1_agc_power.overRangeLowPowerThresh" value="7" /><debug-attribute name="rx1_agc_power.overRangeHighPowerThresh" value="0" /><debug-attribute name="rx1_agc_power.rxTddPowerMeasDelay" value="0" /><debug-attribute name="rx1_agc_power.rxTddPowerMeasDuration" value="0" /><debug-attribute name="rx1_agc_power.powerMeasurementDelay" value="2" /><debug-attribute name="rx1_agc_power.powerMeasurementDuration" value="10" /><debug-attribute name="rx1_agc_power.underRangeLowPowerGainStepRecovery" value="4" /><debug-attribute name="rx1_agc_power.underRangeHighPowerGainStepRecovery" value="2" /><debug-attribute name="rx1_agc_power.underRangeLowPowerThresh" value="4" /><debug-attribute name="rx1_agc_power.underRangeHighPowerThresh" value="10" /><debug-attribute name="rx1_agc_power.powerEnableMeasurement" value="Y" /><debug-attribute name="rx1_agc_enableFastRecoveryLoop" value="N" /><debug-attribute name="rx1_agc_enableSyncPulseForGainCounter" value="N" /><debug-attribute name="rx1_agc_resetOnRxonGainIndex" value="255" /><debug-attribute name="rx1_agc_resetOnRxon" value="N" /><debug-attribute name="rx1_agc_agcMode" value="1" /><debug-attribute name="rx1_agc_changeGainIfThreshHigh" value="3" /><debug-attribute name="rx1_agc_lowThreshPreventGainInc" value="N" /><debug-attribute name="rx1_agc_slowLoopSettlingDelay" value="16" /><debug-attribute name="rx1_agc_attackDelay_us" value="10" /><debug-attribute name="rx1_agc_gainUpdateCounter" value="11520" /><debug-attribute name="rx1_agc_minGainIndex" value="187" /><debug-attribute name="rx1_agc_maxGainIndex" value="255" /><debug-attribute name="rx1_agc_peakWaitTime" value="4" /><debug-attribute name="rx1_ssi_test_mode_configure" value="ERROR" /><debug-attribute name="rx1_ssi_test_mode_fixed_pattern" value="0" /><debug-attribute name="rx1_ssi_test_mode_data" value="TESTMODE_DATA_NORMAL" /><debug-attribute name="rx1_agc_config" value="ERROR" /><debug-attribute name="rx1_gain_control_pin_mode" value="ERROR" /><debug-attribute name="rx1_adc_type" value="HP" /><debug-attribute name="rx0_near_end_loopback" value="ERROR" /><debug-attribute name="rx0_enablement_delays" value="fall_to_off_delay: 0
guard_delay: 0
hold_delay: 0
rise_to_analog_on_delay: 0
rise_to_on_delay: 0" /><debug-attribute name="rx0_rise_to_on_delay_ns" value="0" /><debug-attribute name="rx0_rise_to_analog_delay_ns" value="0" /><debug-attribute name="rx0_hold_delay_ns" value="0" /><debug-attribute name="rx0_guard_delay_ns" value="0" /><debug-attribute name="rx0_fall_to_off_delay_ns" value="0" /><debug-attribute name="rx0_ssi_q_data_delay" value="0" /><debug-attribute name="rx0_ssi_i_data_delay" value="0" /><debug-attribute name="rx0_ssi_strobe_delay" value="0" /><debug-attribute name="rx0_ssi_clk_delay" value="0" /><debug-attribute name="rx0_agc_peak.feedback_apd_high_hb_high" value="0" /><debug-attribute name="rx0_agc_peak.feedback_apd_low_hb_low" value="0" /><debug-attribute name="rx0_agc_peak.hbUnderRangeLowThreshExceededCount" value="3" /><debug-attribute name="rx0_agc_peak.hbUnderRangeMidThreshExceededCount" value="3" /><debug-attribute name="rx0_agc_peak.hbOverloadPowerMode" value="0" /><debug-attribute name="rx0_agc_peak.hbGainStepAttack" value="2" /><debug-attribute name="rx0_agc_peak.hbGainStepMidRecovery" value="4" /><debug-attribute name="rx0_agc_peak.hbGainStepLowRecovery" value="6" /><debug-attribute name="rx0_agc_peak.hbGainStepHighRecovery" value="2" /><debug-attribute name="rx0_agc_peak.hbUnderRangeHighThreshExceededCount" value="3" /><debug-attribute name="rx0_agc_peak.hbUpperThreshPeakExceededCount" value="6" /><debug-attribute name="rx0_agc_peak.hbUnderRangeHighThresh" value="7335" /><debug-attribute name="rx0_agc_peak.hbUnderRangeMidThresh" value="8230" /><debug-attribute name="rx0_agc_peak.hbUnderRangeLowThresh" value="5826" /><debug-attribute name="rx0_agc_peak.hbHighThresh" value="13044" /><debug-attribute name="rx0_agc_peak.hbOverloadThreshCount" value="1" /><debug-attribute name="rx0_agc_peak.hbOverloadDurationCount" value="1" /><debug-attribute name="rx0_agc_peak.enableHbOverload" value="Y" /><debug-attribute name="rx0_agc_peak.apdGainStepRecovery" value="0" /><debug-attribute name="rx0_agc_peak.apdGainStepAttack" value="2" /><debug-attribute name="rx0_agc_peak.apdLowerThreshPeakExceededCount" value="3" /><debug-attribute name="rx0_agc_peak.apdUpperThreshPeakExceededCount" value="6" /><debug-attribute name="rx0_agc_peak.apdLowThresh" value="12" /><debug-attribute name="rx0_agc_peak.apdHighThresh" value="21" /><debug-attribute name="rx0_agc_peak.agcUnderRangeHighInterval" value="4" /><debug-attribute name="rx0_agc_peak.agcUnderRangeMidInterval" value="2" /><debug-attribute name="rx0_agc_peak.agcUnderRangeLowInterval" value="50" /><debug-attribute name="rx0_agc_power.feedback_apd_high_apd_low" value="0" /><debug-attribute name="rx0_agc_power.feedback_inner_high_inner_low" value="0" /><debug-attribute name="rx0_agc_power.overRangeLowPowerGainStepAttack" value="4" /><debug-attribute name="rx0_agc_power.overRangeHighPowerGainStepAttack" value="4" /><debug-attribute name="rx0_agc_power.overRangeLowPowerThresh" value="7" /><debug-attribute name="rx0_agc_power.overRangeHighPowerThresh" value="0" /><debug-attribute name="rx0_agc_power.rxTddPowerMeasDelay" value="0" /><debug-attribute name="rx0_agc_power.rxTddPowerMeasDuration" value="0" /><debug-attribute name="rx0_agc_power.powerMeasurementDelay" value="2" /><debug-attribute name="rx0_agc_power.powerMeasurementDuration" value="10" /><debug-attribute name="rx0_agc_power.underRangeLowPowerGainStepRecovery" value="4" /><debug-attribute name="rx0_agc_power.underRangeHighPowerGainStepRecovery" value="2" /><debug-attribute name="rx0_agc_power.underRangeLowPowerThresh" value="4" /><debug-attribute name="rx0_agc_power.underRangeHighPowerThresh" value="10" /><debug-attribute name="rx0_agc_power.powerEnableMeasurement" value="Y" /><debug-attribute name="rx0_agc_enableFastRecoveryLoop" value="N" /><debug-attribute name="rx0_agc_enableSyncPulseForGainCounter" value="N" /><debug-attribute name="rx0_agc_resetOnRxonGainIndex" value="255" /><debug-attribute name="rx0_agc_resetOnRxon" value="N" /><debug-attribute name="rx0_agc_agcMode" value="1" /><debug-attribute name="rx0_agc_changeGainIfThreshHigh" value="3" /><debug-attribute name="rx0_agc_lowThreshPreventGainInc" value="N" /><debug-attribute name="rx0_agc_slowLoopSettlingDelay" value="16" /><debug-attribute name="rx0_agc_attackDelay_us" value="10" /><debug-attribute name="rx0_agc_gainUpdateCounter" value="11520" /><debug-attribute name="rx0_agc_minGainIndex" value="187" /><debug-attribute name="rx0_agc_maxGainIndex" value="255" /><debug-attribute name="rx0_agc_peakWaitTime" value="4" /><debug-attribute name="rx0_ssi_test_mode_configure" value="ERROR" /><debug-attribute name="rx0_ssi_test_mode_fixed_pattern" value="0" /><debug-attribute name="rx0_ssi_test_mode_data" value="TESTMODE_DATA_NORMAL" /><debug-attribute name="rx0_agc_config" value="ERROR" /><debug-attribute name="rx0_gain_control_pin_mode" value="ERROR" /><debug-attribute name="rx0_adc_type" value="HP" /><debug-attribute name="tx1_enablement_delays" value="fall_to_off_delay: 0
guard_delay: 0
hold_delay: 0
rise_to_analog_on_delay: 0