<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE context [
        <!ELEMENT context (device | context-attribute)*>
        <!ELEMENT context-attribute EMPTY>
        <!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*>
        <!ELEMENT channel (scan-element?, attribute*)>
        <!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY>
        <!ELEMENT debug-attribute EMPTY>
        <!ELEMENT buffer-attribute EMPTY>
        <!ATTLIST context version-major CDATA #IMPLIED version-minor CDATA #IMPLIED name CDATA #IMPLIED description CDATA #IMPLIED version-git CDATA #IMPLIED>
        <!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED>
        <!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED label CDATA #IMPLIED>
        <!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED>
        <!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED>
        <!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED value CDATA #IMPLIED>
        <!ATTLIST debug-attribute name CDATA #REQUIRED value CDATA #IMPLIED>
        <!ATTLIST buffer-attribute name CDATA #REQUIRED value CDATA #IMPLIED>
    ]>
<context name="xml" version-major="0" version-minor="25" version-git="v0.25" description="Linux analog 6.6.0-xilinx-v2023.2-25389-g72fa72741120 #1 SMP Tue Sep  9 13:25:01 UTC 2025 aarch64">
  <context-attribute name="unique_id" value="1044000a38190006ffff1d00e5b71b0e5c"/>
  <context-attribute name="local,kernel" value="6.6.0-xilinx-v2023.2-25389-g72fa72741120"/>
  <context-attribute name="uri" value="local:"/>
  <device id="hwmon0" name="ff0b0000ethernetffffffff01">
    <channel id="temp1" type="input">
      <attribute name="crit" filename="temp1_crit" value="100000"/>
      <attribute name="input" filename="temp1_input" value="36000"/>
      <attribute name="max_alarm" filename="temp1_max_alarm" value="0"/>
    </channel>
  </device>
  <device id="iio:device0" name="xilinx-ams">
    <channel id="voltage9" type="input">
      <attribute name="raw" filename="in_voltage9_raw" value="18432"/>
      <attribute name="scale" filename="in_voltage9_scale" value="0.045776367"/>
    </channel>
    <channel id="temp20" type="input">
      <attribute name="input" filename="in_temp20_input" value="35826"/>
      <attribute name="offset" filename="in_temp20_offset" value="-36058"/>
      <attribute name="raw" filename="in_temp20_raw" value="40724"/>
      <attribute name="scale" filename="in_temp20_scale" value="7.771514892"/>
    </channel>
    <channel id="voltage11" type="input">
      <attribute name="raw" filename="in_voltage11_raw" value="39216"/>
      <attribute name="scale" filename="in_voltage11_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage23" type="input">
      <attribute name="raw" filename="in_voltage23_raw" value="27343"/>
      <attribute name="scale" filename="in_voltage23_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage15" type="input">
      <attribute name="raw" filename="in_voltage15_raw" value="19454"/>
      <attribute name="scale" filename="in_voltage15_scale" value="0.091552734"/>
    </channel>
    <channel id="voltage2" type="input">
      <attribute name="raw" filename="in_voltage2_raw" value="18461"/>
      <attribute name="scale" filename="in_voltage2_scale" value="0.045776367"/>
    </channel>
    <channel id="temp8" type="input">
      <attribute name="input" filename="in_temp8_input" value="36666"/>
      <attribute name="offset" filename="in_temp8_offset" value="-36058"/>
      <attribute name="raw" filename="in_temp8_raw" value="40586"/>
      <attribute name="scale" filename="in_temp8_scale" value="7.771514892"/>
    </channel>
    <channel id="voltage19" type="input">
      <attribute name="raw" filename="in_voltage19_raw" value="39102"/>
      <attribute name="scale" filename="in_voltage19_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage17" type="input">
      <attribute name="raw" filename="in_voltage17_raw" value="18434"/>
      <attribute name="scale" filename="in_voltage17_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage22" type="input">
      <attribute name="raw" filename="in_voltage22_raw" value="39277"/>
      <attribute name="scale" filename="in_voltage22_scale" value="0.045776367"/>
    </channel>
    <channel id="temp7" type="input">
      <attribute name="input" filename="in_temp7_input" value="36899"/>
      <attribute name="offset" filename="in_temp7_offset" value="-36058"/>
      <attribute name="raw" filename="in_temp7_raw" value="40748"/>
      <attribute name="scale" filename="in_temp7_scale" value="7.771514892"/>
    </channel>
    <channel id="voltage1" type="input">
      <attribute name="raw" filename="in_voltage1_raw" value="32620"/>
      <attribute name="scale" filename="in_voltage1_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage26" type="input">
      <attribute name="raw" filename="in_voltage26_raw" value="18468"/>
      <attribute name="scale" filename="in_voltage26_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage27" type="input">
      <attribute name="raw" filename="in_voltage27_raw" value="18462"/>
      <attribute name="scale" filename="in_voltage27_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage10" type="input">
      <attribute name="raw" filename="in_voltage10_raw" value="18389"/>
      <attribute name="scale" filename="in_voltage10_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage5" type="input">
      <attribute name="raw" filename="in_voltage5_raw" value="39212"/>
      <attribute name="scale" filename="in_voltage5_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage6" type="input">
      <attribute name="raw" filename="in_voltage6_raw" value="18484"/>
      <attribute name="scale" filename="in_voltage6_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage14" type="input">
      <attribute name="raw" filename="in_voltage14_raw" value="19505"/>
      <attribute name="scale" filename="in_voltage14_scale" value="0.091552734"/>
    </channel>
    <channel id="voltage12" type="input">
      <attribute name="raw" filename="in_voltage12_raw" value="26053"/>
      <attribute name="scale" filename="in_voltage12_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage16" type="input">
      <attribute name="raw" filename="in_voltage16_raw" value="36437"/>
      <attribute name="scale" filename="in_voltage16_scale" value="0.091552734"/>
    </channel>
    <channel id="voltage24" type="input">
      <attribute name="raw" filename="in_voltage24_raw" value="0"/>
      <attribute name="scale" filename="in_voltage24_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage3" type="input">
      <attribute name="raw" filename="in_voltage3_raw" value="18566"/>
      <attribute name="scale" filename="in_voltage3_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage18" type="input">
      <attribute name="raw" filename="in_voltage18_raw" value="38871"/>
      <attribute name="scale" filename="in_voltage18_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage28" type="input">
      <attribute name="raw" filename="in_voltage28_raw" value="39264"/>
      <attribute name="scale" filename="in_voltage28_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage21" type="input">
      <attribute name="raw" filename="in_voltage21_raw" value="18686"/>
      <attribute name="scale" filename="in_voltage21_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage0" type="input">
      <attribute name="raw" filename="in_voltage0_raw" value="26266"/>
      <attribute name="scale" filename="in_voltage0_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage13" type="input">
      <attribute name="raw" filename="in_voltage13_raw" value="19505"/>
      <attribute name="scale" filename="in_voltage13_scale" value="0.091552734"/>
    </channel>
    <channel id="voltage25" type="input">
      <attribute name="raw" filename="in_voltage25_raw" value="18594"/>
      <attribute name="scale" filename="in_voltage25_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage4" type="input">
      <attribute name="raw" filename="in_voltage4_raw" value="39220"/>
      <attribute name="scale" filename="in_voltage4_scale" value="0.045776367"/>
    </channel>
    <channel id="voltage29" type="input">
      <attribute name="raw" filename="in_voltage29_raw" value="39246"/>
      <attribute name="scale" filename="in_voltage29_scale" value="0.045776367"/>
    </channel>
    <attribute name="waiting_for_supplier" value="0"/>
  </device>
  <device id="iio:device1" name="adf4382">
    <channel id="altvoltage1" type="output">
      <attribute name="en" filename="out_altvoltage1_en" value="1"/>
      <attribute name="en_auto_align" filename="out_altvoltage_en_auto_align" value="0"/>
      <attribute name="frequency" filename="out_altvoltage_frequency" value="20000000000"/>
      <attribute name="hardwaregain" filename="out_altvoltage1_hardwaregain" value="0"/>
      <attribute name="phase" filename="out_altvoltage_phase" value="0"/>
    </channel>
    <channel id="altvoltage0" type="output">
      <attribute name="en" filename="out_altvoltage0_en" value="1"/>
      <attribute name="en_auto_align" filename="out_altvoltage_en_auto_align" value="0"/>
      <attribute name="frequency" filename="out_altvoltage_frequency" value="20000000000"/>
      <attribute name="hardwaregain" filename="out_altvoltage0_hardwaregain" value="11"/>
      <attribute name="phase" filename="out_altvoltage_phase" value="0"/>
    </channel>
    <channel id="temp0" type="input">
      <attribute name="input" filename="in_temp0_input" value="63000"/>
    </channel>
    <attribute name="waiting_for_supplier" value="0"/>
    <debug-attribute name="coarse_current" value="0"/>
    <debug-attribute name="fine_current" value="0"/>
    <debug-attribute name="bleed_pol" value="0"/>
    <debug-attribute name="del_cnt_raw" value="0"/>
    <debug-attribute name="direct_reg_access" value="0x18"/>
  </device>
  <device id="iio:device2" name="ltc6952" label="ltc6952">
    <channel id="altvoltage5" name="Apollo SYSREF" type="output">
      <attribute name="frequency" filename="out_altvoltage5_Apollo SYSREF_frequency" value="3255208"/>
      <attribute name="label" filename="out_altvoltage5_Apollo SYSREF_label" value="Apollo SYSREF"/>
      <attribute name="phase" filename="out_altvoltage5_Apollo SYSREF_phase" value="0.000000"/>
    </channel>
    <channel id="altvoltage3" name="VUP Core CLK" type="output">
      <attribute name="frequency" filename="out_altvoltage3_VUP Core CLK_frequency" value="312500000"/>
      <attribute name="label" filename="out_altvoltage3_VUP Core CLK_label" value="VUP Core CLK"/>
      <attribute name="phase" filename="out_altvoltage3_VUP Core CLK_phase" value="0.000000"/>
    </channel>
    <channel id="altvoltage7" name="JESD REF CLK 2" type="output">
      <attribute name="frequency" filename="out_altvoltage7_JESD REF CLK 2_frequency" value="312500000"/>
      <attribute name="label" filename="out_altvoltage7_JESD REF CLK 2_label" value="JESD REF CLK 2"/>
      <attribute name="phase" filename="out_altvoltage7_JESD REF CLK 2_phase" value="0.000000"/>
    </channel>
    <channel id="altvoltage4" name="VUP JESD SYSREF" type="output">
      <attribute name="frequency" filename="out_altvoltage4_VUP JESD SYSREF_frequency" value="3255208"/>
      <attribute name="label" filename="out_altvoltage4_VUP JESD SYSREF_label" value="VUP JESD SYSREF"/>
      <attribute name="phase" filename="out_altvoltage4_VUP JESD SYSREF_phase" value="0.000000"/>
    </channel>
    <channel id="altvoltage6" name="JESD REF CLK 1" type="output">
      <attribute name="frequency" filename="out_altvoltage6_JESD REF CLK 1_frequency" value="312500000"/>
      <attribute name="label" filename="out_altvoltage6_JESD REF CLK 1_label" value="JESD REF CLK 1"/>
      <attribute name="phase" filename="out_altvoltage6_JESD REF CLK 1_phase" value="0.000000"/>
    </channel>
    <attribute name="waiting_for_supplier" value="0"/>
    <debug-attribute name="status" value="REF Status:&#9;Valid&#10;VCO Status:&#9;Valid&#10;Lock Status:&#9;PLL Locked"/>
    <debug-attribute name="direct_reg_access" value="0x15"/>
  </device>
  <device id="iio:device5" name="axi-ad9084-tx-hpc">
    <channel id="voltage0_i" type="output">
      <scan-element index="0" format="le:S16/16&gt;&gt;0"/>
      <attribute name="calibphase" filename="out_voltage0_i_calibphase" value="0.000000"/>
      <attribute name="calibscale" filename="out_voltage0_i_calibscale" value="1.000000"/>
      <attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" value="20000000000"/>
    </channel>
    <channel id="voltage0_q" type="output">
      <scan-element index="1" format="le:S16/16&gt;&gt;0"/>
      <attribute name="calibphase" filename="out_voltage0_q_calibphase" value="0.000000"/>
      <attribute name="calibscale" filename="out_voltage0_q_calibscale" value="1.000000"/>
      <attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" value="20000000000"/>
    </channel>
    <channel id="voltage1_i" type="output">
      <scan-element index="2" format="le:S16/16&gt;&gt;0"/>
      <attribute name="calibphase" filename="out_voltage1_i_calibphase" value="0.000000"/>
      <attribute name="calibscale" filename="out_voltage1_i_calibscale" value="1.000000"/>
      <attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" value="20000000000"/>
    </channel>
    <channel id="voltage1_q" type="output">
      <scan-element index="3" format="le:S16/16&gt;&gt;0"/>
      <attribute name="calibphase" filename="out_voltage1_q_calibphase" value="0.000000"/>
      <attribute name="calibscale" filename="out_voltage1_q_calibscale" value="1.000000"/>
      <attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" value="20000000000"/>
    </channel>
    <channel id="altvoltage3" name="TX1_Q_F2" type="output">
      <attribute name="frequency" filename="out_altvoltage3_TX1_Q_F2_frequency" value="39978637"/>
      <attribute name="label" filename="out_altvoltage3_TX1_Q_F2_label" value="TX1_Q_F2"/>
      <attribute name="phase" filename="out_altvoltage3_TX1_Q_F2_phase" value="0"/>
      <attribute name="raw" filename="out_altvoltage3_TX1_Q_F2_raw" value="1"/>
      <attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" value="20000000000"/>
      <attribute name="scale" filename="out_altvoltage3_TX1_Q_F2_scale" value="0.250000"/>
    </channel>
    <channel id="altvoltage5" name="TX2_I_F2" type="output">
      <attribute name="frequency" filename="out_altvoltage5_TX2_I_F2_frequency" value="39978637"/>
      <attribute name="label" filename="out_altvoltage5_TX2_I_F2_label" value="TX2_I_F2"/>
      <attribute name="phase" filename="out_altvoltage5_TX2_I_F2_phase" value="90000"/>
      <attribute name="raw" filename="out_altvoltage5_TX2_I_F2_raw" value="1"/>
      <attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" value="20000000000"/>
      <attribute name="scale" filename="out_altvoltage5_TX2_I_F2_scale" value="0.250000"/>
    </channel>
    <channel id="altvoltage2" name="TX1_Q_F1" type="output">
      <attribute name="frequency" filename="out_altvoltage2_TX1_Q_F1_frequency" value="39978637"/>
      <attribute name="label" filename="out_altvoltage2_TX1_Q_F1_label" value="TX1_Q_F1"/>
      <attribute name="phase" filename="out_altvoltage2_TX1_Q_F1_phase" value="0"/>
      <attribute name="raw" filename="out_altvoltage2_TX1_Q_F1_raw" value="1"/>
      <attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" value="20000000000"/>
      <attribute name="scale" filename="out_altvoltage2_TX1_Q_F1_scale" value="0.250000"/>
    </channel>
    <channel id="altvoltage1" name="TX1_I_F2" type="output">
      <attribute name="frequency" filename="out_altvoltage1_TX1_I_F2_frequency" value="39978637"/>
      <attribute name="label" filename="out_altvoltage1_TX1_I_F2_label" value="TX1_I_F2"/>
      <attribute name="phase" filename="out_altvoltage1_TX1_I_F2_phase" value="90000"/>
      <attribute name="raw" filename="out_altvoltage1_TX1_I_F2_raw" value="1"/>
      <attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" value="20000000000"/>
      <attribute name="scale" filename="out_altvoltage1_TX1_I_F2_scale" value="0.250000"/>
    </channel>
    <channel id="altvoltage7" name="TX2_Q_F2" type="output">
      <attribute name="frequency" filename="out_altvoltage7_TX2_Q_F2_frequency" value="39978637"/>
      <attribute name="label" filename="out_altvoltage7_TX2_Q_F2_label" value="TX2_Q_F2"/>
      <attribute name="phase" filename="out_altvoltage7_TX2_Q_F2_phase" value="0"/>
      <attribute name="raw" filename="out_altvoltage7_TX2_Q_F2_raw" value="1"/>
      <attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" value="20000000000"/>
      <attribute name="scale" filename="out_altvoltage7_TX2_Q_F2_scale" value="0.250000"/>
    </channel>
    <channel id="altvoltage4" name="TX2_I_F1" type="output">
      <attribute name="frequency" filename="out_altvoltage4_TX2_I_F1_frequency" value="39978637"/>
      <attribute name="label" filename="out_altvoltage4_TX2_I_F1_label" value="TX2_I_F1"/>
      <attribute name="phase" filename="out_altvoltage4_TX2_I_F1_phase" value="90000"/>
      <attribute name="raw" filename="out_altvoltage4_TX2_I_F1_raw" value="1"/>
      <attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" value="20000000000"/>
      <attribute name="scale" filename="out_altvoltage4_TX2_I_F1_scale" value="0.250000"/>
    </channel>
    <channel id="altvoltage0" name="TX1_I_F1" type="output">
      <attribute name="frequency" filename="out_altvoltage0_TX1_I_F1_frequency" value="39978637"/>
      <attribute name="label" filename="out_altvoltage0_TX1_I_F1_label" value="TX1_I_F1"/>
      <attribute name="phase" filename="out_altvoltage0_TX1_I_F1_phase" value="90000"/>
      <attribute name="raw" filename="out_altvoltage0_TX1_I_F1_raw" value="1"/>
      <attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" value="20000000000"/>
      <attribute name="scale" filename="out_altvoltage0_TX1_I_F1_scale" value="0.250000"/>
    </channel>
    <channel id="altvoltage6" name="TX2_Q_F1" type="output">
      <attribute name="frequency" filename="out_altvoltage6_TX2_Q_F1_frequency" value="39978637"/>
      <attribute name="label" filename="out_altvoltage6_TX2_Q_F1_label" value="TX2_Q_F1"/>
      <attribute name="phase" filename="out_altvoltage6_TX2_Q_F1_phase" value="0"/>
      <attribute name="raw" filename="out_altvoltage6_TX2_Q_F1_raw" value="1"/>
      <attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" value="20000000000"/>
      <attribute name="scale" filename="out_altvoltage6_TX2_Q_F1_scale" value="0.250000"/>
    </channel>
    <attribute name="sync_start_enable" value="disarm"/>
    <attribute name="sync_start_enable_available" value="arm disarm trigger_manual"/>
    <attribute name="waiting_for_supplier" value="0"/>
    <buffer-attribute name="data_available" value="0"/>
    <buffer-attribute name="direction" value="out"/>
    <buffer-attribute name="length_align_bytes" value="32"/>
    <debug-attribute name="pl_ddr_fifo_enable" value="1"/>
    <debug-attribute name="direct_reg_access" value="0x90262"/>
  </device>
  <device id="iio:device6" name="axi-ad9084-rx-hpc">
    <channel id="voltage0_i" type="input">
      <scan-element index="0" format="le:s12/16&gt;&gt;0"/>
      <attribute name="adc_frequency" filename="in_voltage_adc_frequency" value="20000000000"/>
      <attribute name="cfir_en" filename="in_voltage0_i_cfir_en" value="0"/>
      <attribute name="cfir_profile_sel" filename="in_voltage0_i_cfir_profile_sel" value="0"/>
      <attribute name="channel_6db_digital_gain_en" filename="in_voltage0_i_channel_6db_digital_gain_en" value="0"/>
      <attribute name="channel_nco_frequency" filename="in_voltage0_i_channel_nco_frequency" value="0"/>
      <attribute name="channel_nco_frequency_available" filename="in_voltage_channel_nco_frequency_available" value="[-10000000000 1 10000000000]"/>
      <attribute name="channel_nco_mixer_mode" filename="in_voltage0_i_channel_nco_mixer_mode" value="var_IF"/>
      <attribute name="channel_nco_mixer_mode_available" filename="in_voltage_channel_nco_mixer_mode_available" value="var_IF zero_IF fs/4_IF test_tone"/>
      <attribute name="channel_nco_phase" filename="in_voltage0_i_channel_nco_phase" value="0"/>
      <attribute name="channel_nco_test_tone_scale" filename="in_voltage0_i_channel_nco_test_tone_scale" value="0.000000000"/>
      <attribute name="en" filename="in_voltage0_i_en" value="1"/>
      <attribute name="ffh_cnco_frequency" filename="in_voltage0_i_ffh_cnco_frequency" value="0"/>
      <attribute name="ffh_cnco_index" filename="in_voltage0_i_ffh_cnco_index" value="0"/>
      <attribute name="ffh_cnco_mode" filename="in_voltage0_i_ffh_cnco_mode" value="4"/>
      <attribute name="ffh_cnco_select" filename="in_voltage0_i_ffh_cnco_select" value="0"/>
      <attribute name="ffh_fnco_frequency" filename="in_voltage0_i_ffh_fnco_frequency" value="0"/>
      <attribute name="ffh_fnco_index" filename="in_voltage0_i_ffh_fnco_index" value="0"/>
      <attribute name="ffh_fnco_mode" filename="in_voltage0_i_ffh_fnco_mode" value="4"/>
      <attribute name="ffh_fnco_select" filename="in_voltage0_i_ffh_fnco_select" value="-1"/>
      <attribute name="label" filename="in_voltage0_i_label" value="Side-A:FDDC0-&gt;CDDC0-&gt;ADC0"/>
      <attribute name="loopback" filename="in_voltage0_i_loopback" value="off"/>
      <attribute name="loopback_available" filename="in_voltage_loopback_available" value="off loopback0 loopback1 loopback2 loopback3_jesd"/>
      <attribute name="main_hb1_6db_digital_gain_en" filename="in_voltage0_i_main_hb1_6db_digital_gain_en" value="0"/>
      <attribute name="main_nco_frequency" filename="in_voltage0_i_main_nco_frequency" value="0"/>
      <attribute name="main_nco_frequency_available" filename="in_voltage_main_nco_frequency_available" value="[-10000000000 1 10000000000]"/>
      <attribute name="main_nco_mixer_mode" filename="in_voltage0_i_main_nco_mixer_mode" value="var_IF"/>
      <attribute name="main_nco_mixer_mode_available" filename="in_voltage_main_nco_mixer_mode_available" value="var_IF zero_IF fs/4_IF test_tone"/>
      <attribute name="main_nco_phase" filename="in_voltage0_i_main_nco_phase" value="0"/>
      <attribute name="main_nco_test_tone_scale" filename="in_voltage0_i_main_nco_test_tone_scale" value="0.000000000"/>
      <attribute name="main_tb1_6db_digital_gain_en" filename="in_voltage0_i_main_tb1_6db_digital_gain_en" value="0"/>
      <attribute name="nyquist_zone" filename="in_voltage0_i_nyquist_zone" value="odd"/>
      <attribute name="nyquist_zone_available" filename="in_voltage_nyquist_zone_available" value="odd even"/>
      <attribute name="sampling_frequency" filename="in_voltage_sampling_frequency" value="20000000000"/>
      <attribute name="test_mode" filename="in_voltage0_i_test_mode" value="off"/>
      <attribute name="test_mode_available" filename="in_voltage_test_mode_available" value="off midscale_short pos_fullscale neg_fullscale checkerboard pn23 pn9 one_zero_toggle user pn7 pn15 pn31    ramp"/>
    </channel>
    <channel id="voltage0_q" type="output">
      <attribute name="cfir_en" filename="out_voltage0_q_cfir_en" value="0"/>
      <attribute name="cfir_profile_sel" filename="out_voltage0_q_cfir_profile_sel" value="0"/>
      <attribute name="channel_nco_frequency" filename="out_voltage0_q_channel_nco_frequency" value="0"/>
      <attribute name="channel_nco_frequency_available" filename="out_voltage_channel_nco_frequency_available" value="[-10000000000 1 10000000000]"/>
      <attribute name="channel_nco_gain_scale" filename="out_voltage0_q_channel_nco_gain_scale" value="ERROR"/>
      <attribute name="channel_nco_mixer_mode" filename="out_voltage0_q_channel_nco_mixer_mode" value="var_IF"/>
      <attribute name="channel_nco_mixer_mode_available" filename="out_voltage_channel_nco_mixer_mode_available" value="var_IF zero_IF fs/4_IF test_tone"/>
      <attribute name="channel_nco_phase" filename="out_voltage0_q_channel_nco_phase" value="0"/>
      <attribute name="channel_nco_test_tone_en" filename="out_voltage0_q_channel_nco_test_tone_en" value="0"/>
      <attribute name="channel_nco_test_tone_scale" filename="out_voltage0_q_channel_nco_test_tone_scale" value="0.000000000"/>
      <attribute name="dac_frequency" filename="out_voltage_dac_frequency" value="20000000000"/>
      <attribute name="en" filename="out_voltage0_q_en" value="1"/>
      <attribute name="ffh_cnco_frequency" filename="out_voltage0_q_ffh_cnco_frequency" value="0"/>
      <attribute name="ffh_cnco_index" filename="out_voltage0_q_ffh_cnco_index" value="0"/>
      <attribute name="ffh_cnco_mode" filename="out_voltage0_q_ffh_cnco_mode" value="4"/>
      <attribute name="ffh_cnco_select" filename="out_voltage0_q_ffh_cnco_select" value="0"/>
      <attribute name="ffh_fnco_frequency" filename="out_voltage0_q_ffh_fnco_frequency" value="0"/>
      <attribute name="ffh_fnco_index" filename="out_voltage0_q_ffh_fnco_index" value="0"/>
      <attribute name="ffh_fnco_mode" filename="out_voltage0_q_ffh_fnco_mode" value="4"/>
      <attribute name="ffh_fnco_select" filename="out_voltage0_q_ffh_fnco_select" value="-1"/>
      <attribute name="invsinc_en" filename="out_voltage0_q_invsinc_en" value="1"/>
      <attribute name="label" filename="out_voltage0_q_label" value="Side-A:FDUC0-&gt;CDUC0-&gt;DAC0"/>
      <attribute name="main_nco_frequency" filename="out_voltage0_q_main_nco_frequency" value="0"/>
      <attribute name="main_nco_frequency_available" filename="out_voltage_main_nco_frequency_available" value="[-10000000000 1 10000000000]"/>
      <attribute name="main_nco_mixer_mode" filename="out_voltage0_q_main_nco_mixer_mode" value="var_IF"/>
      <attribute name="main_nco_mixer_mode_available" filename="out_voltage_main_nco_mixer_mode_available" value="var_IF zero_IF fs/4_IF test_tone"/>
      <attribute name="main_nco_phase" filename="out_voltage0_q_main_nco_phase" value="0"/>
      <attribute name="main_nco_test_tone_en" filename="out_voltage0_q_main_nco_test_tone_en" value="0"/>
      <attribute name="main_nco_test_tone_scale" filename="out_voltage0_q_main_nco_test_tone_scale" value="0.000000000"/>
      <attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" value="20000000000"/>
    </channel>
    <channel id="voltage0_q" type="input">
      <attribute name="adc_frequency" filename="in_voltage_adc_frequency" value="20000000000"/>
      <attribute name="cfir_en" filename="in_voltage0_q_cfir_en" value="0"/>
      <attribute name="cfir_profile_sel" filename="in_voltage0_q_cfir_profile_sel" value="0"/>
      <attribute name="channel_6db_digital_gain_en" filename="in_voltage0_q_channel_6db_digital_gain_en" value="0"/>
      <attribute name="channel_nco_frequency" filename="in_voltage0_q_channel_nco_frequency" value="0"/>
      <attribute name="channel_nco_frequency_available" filename="in_voltage_channel_nco_frequency_available" value="[-10000000000 1 10000000000]"/>
      <attribute name="channel_nco_mixer_mode" filename="in_voltage0_q_channel_nco_mixer_mode" value="var_IF"/>
      <attribute name="channel_nco_mixer_mode_available" filename="in_voltage_channel_nco_mixer_mode_available" value="var_IF zero_IF fs/4_IF test_tone"/>
      <attribute name="channel_nco_phase" filename="in_voltage0_q_channel_nco_phase" value="0"/>
      <attribute name="channel_nco_test_tone_scale" filename="in_voltage0_q_channel_nco_test_tone_scale" value="0.000000000"/>
      <attribute name="en" filename="in_voltage0_q_en" value="1"/>
      <attribute name="ffh_cnco_frequency" filename="in_voltage0_q_ffh_cnco_frequency" value="0"/>
      <attribute name="ffh_cnco_index" filename="in_voltage0_q_ffh_cnco_index" value="0"/>
      <attribute name="ffh_cnco_mode" filename="in_voltage0_q_ffh_cnco_mode" value="4"/>
      <attribute name="ffh_cnco_select" filename="in_voltage0_q_ffh_cnco_select" value="0"/>
      <attribute name="ffh_fnco_frequency" filename="in_voltage0_q_ffh_fnco_frequency" value="0"/>
      <attribute name="ffh_fnco_index" filename="in_voltage0_q_ffh_fnco_index" value="0"/>
      <attribute name="ffh_fnco_mode" filename="in_voltage0_q_ffh_fnco_mode" value="4"/>
      <attribute name="ffh_fnco_select" filename="in_voltage0_q_ffh_fnco_select" value="-1"/>
      <attribute name="label" filename="in_voltage0_q_label" value="Side-A:FDDC0-&gt;CDDC0-&gt;ADC0"/>
      <attribute name="loopback" filename="in_voltage0_q_loopback" value="off"/>
      <attribute name="loopback_available" filename="in_voltage_loopback_available" value="off loopback0 loopback1 loopback2 loopback3_jesd"/>
      <attribute name="main_hb1_6db_digital_gain_en" filename="in_voltage0_q_main_hb1_6db_digital_gain_en" value="0"/>
      <attribute name="main_nco_frequency" filename="in_voltage0_q_main_nco_frequency" value="0"/>