<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED version-major CDATA #REQUIRED version-minor CDATA #REQUIRED version-git CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED label CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED><!ATTLIST buffer-attribute name CDATA #REQUIRED>]><context name="xml" version-major="0" version-minor="25" version-git="5ab436a" description="no-OS/projects/NO_OS_PROJECT NO_OS_VERSION" ><device id="iio:device0" name="swiot" ><attribute name="serial_id" /><attribute name="mode" /><attribute name="mode_available" /><attribute name="identify" /><attribute name="ext_psu" /><attribute name="ch0_enable" /><attribute name="ch1_enable" /><attribute name="ch2_enable" /><attribute name="ch3_enable" /><attribute name="ch0_function" /><attribute name="ch1_function" /><attribute name="ch2_function" /><attribute name="ch3_function" /><attribute name="ch0_device" /><attribute name="ch1_device" /><attribute name="ch2_device" /><attribute name="ch3_device" /><attribute name="ch0_function_available" /><attribute name="ch1_function_available" /><attribute name="ch2_function_available" /><attribute name="ch3_function_available" /><attribute name="ch0_device_available" /><attribute name="ch1_device_available" /><attribute name="ch2_device_available" /><attribute name="ch3_device_available" /></device><device id="iio:device1" name="max14906" ><channel id="voltage3" type="output" ><attribute name="raw" filename="out_voltage3_raw" /><attribute name="offset" filename="out_voltage3_offset" /><attribute name="scale" filename="out_voltage3_scale" /><attribute name="do_mode" filename="out_voltage3_do_mode" /><attribute name="do_mode_available" filename="do_mode_available" /><attribute name="current_limit" filename="out_voltage3_current_limit" /><attribute name="current_limit_available" filename="current_limit_available" /></channel><debug-attribute name="direct_reg_access" /></device><device id="iio:device2" name="adt75" ><channel id="temp" name="temp" type="input" ><scan-element index="0" format="le:s12/16&gt;&gt;4" /><attribute name="raw" filename="in_temp_raw" /><attribute name="scale" filename="in_temp_scale" /><attribute name="offset" filename="in_temp_offset" /></channel></device><device id="iio:device3" name="ad74413r" ><channel id="voltage0" type="input" ><scan-element index="0" format="be:u16/32&gt;&gt;8" /><attribute name="sampling_frequency" filename="in_voltage0_sampling_frequency" /><attribute name="sampling_frequency_available" filename="in_voltage0_sampling_frequency_available" /><attribute name="raw" filename="in_voltage0_raw" /><attribute name="scale" filename="in_voltage0_scale" /><attribute name="offset" filename="in_voltage0_offset" /></channel><channel id="voltage1" type="input" ><scan-element index="1" format="be:u16/32&gt;&gt;8" /><attribute name="sampling_frequency" filename="in_voltage1_sampling_frequency" /><attribute name="sampling_frequency_available" filename="in_voltage1_sampling_frequency_available" /><attribute name="raw" filename="in_voltage1_raw" /><attribute name="scale" filename="in_voltage1_scale" /><attribute name="offset" filename="in_voltage1_offset" /></channel><channel id="current2" type="input" ><scan-element index="2" format="be:u16/32&gt;&gt;8" /><attribute name="sampling_frequency" filename="in_current2_sampling_frequency" /><attribute name="sampling_frequency_available" filename="in_current2_sampling_frequency_available" /><attribute name="raw" filename="in_current2_raw" /><attribute name="scale" filename="in_current2_scale" /><attribute name="offset" filename="in_current2_offset" /></channel><channel id="voltage4" type="input" ><scan-element index="3" format="be:u16/32&gt;&gt;8" /><attribute name="sampling_frequency" filename="in_voltage4_sampling_frequency" /><attribute name="sampling_frequency_available" filename="in_voltage4_sampling_frequency_available" /><attribute name="diag_function" filename="in_voltage4_diag_function" /><attribute name="diag_function_available" filename="diag_function_available" /><attribute name="raw" filename="in_voltage4_raw" /><attribute name="scale" filename="in_voltage4_scale" /><attribute name="offset" filename="in_voltage4_offset" /></channel><channel id="voltage5" type="input" ><scan-element index="4" format="be:u16/32&gt;&gt;8" /><attribute name="sampling_frequency" filename="in_voltage5_sampling_frequency" /><attribute name="sampling_frequency_available" filename="in_voltage5_sampling_frequency_available" /><attribute name="diag_function" filename="in_voltage5_diag_function" /><attribute name="diag_function_available" filename="diag_function_available" /><attribute name="raw" filename="in_voltage5_raw" /><attribute name="scale" filename="in_voltage5_scale" /><attribute name="offset" filename="in_voltage5_offset" /></channel><channel id="voltage6" type="input" ><scan-element index="5" format="be:u16/32&gt;&gt;8" /><attribute name="sampling_frequency" filename="in_voltage6_sampling_frequency" /><attribute name="sampling_frequency_available" filename="in_voltage6_sampling_frequency_available" /><attribute name="diag_function" filename="in_voltage6_diag_function" /><attribute name="diag_function_available" filename="diag_function_available" /><attribute name="raw" filename="in_voltage6_raw" /><attribute name="scale" filename="in_voltage6_scale" /><attribute name="offset" filename="in_voltage6_offset" /></channel><channel id="voltage7" type="input" ><scan-element index="6" format="be:u16/32&gt;&gt;8" /><attribute name="sampling_frequency" filename="in_voltage7_sampling_frequency" /><attribute name="sampling_frequency_available" filename="in_voltage7_sampling_frequency_available" /><attribute name="diag_function" filename="in_voltage7_diag_function" /><attribute name="diag_function_available" filename="diag_function_available" /><attribute name="raw" filename="in_voltage7_raw" /><attribute name="scale" filename="in_voltage7_scale" /><attribute name="offset" filename="in_voltage7_offset" /></channel><debug-attribute name="direct_reg_access" /></device><device id="trigger0" name="sw_trig" ></device><device id="trigger1" name="ad74413r-dev0" ></device></context>